### ISSUE TITLE
Extensive memory consumption by dd-trace worker

### ISSUE THREAD

**Issue by agyant** [DataDog/dd-trace-rb#1012]
Hi,
 I am currently using the following dependencies in my application
`ddtrace`: 0.34.2
`rails` (or other framework):Rails 5.2.4.1
`sidekiq`: sidekiq 6.0.5
 
with the following configuration 
```
Datadog.configure do |c|
  c.tracer tags: { env: ENV['RAILS_ENV'] }
  c.tracer partial_flush: true
  # Rails
  c.use :rails,
        service_name: '***',
        database_service: 'mysql',
        distributed_tracing: true,
        analytics_enabled: true

  c.use :active_record, analytics_enabled: true
  c.use :faraday, distributed_tracing: true
  c.use :redis, service_name: 'redis_service'
  c.use :sidekiq, service_name: 'sidekiq', client_service_name: 'sidekiq-client'
  c.use :http
end
```  
Some of the sidekiq workers are using the `gauge`, `increment` and `time` functions.
We are seeing a memory bloat in our application and when I got the trace I can see a similar consumption for many generations:
```
allocated by memory (3355900) (in bytes)
==============================
  3147408  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/workers.rb:78
    39376  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:198
    35952  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:68
    28784  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:69
    18404  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:186
    18232  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:168

object count (2154)
==============================
  214  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:186
  214  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:198
  214  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:68
  214  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:69
  212  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:168
  108  /usr/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/core_ext/numeric/conversions.rb:107
  108  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/utils.rb:15
  104  /usr/bundle/ruby/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:39


High Ref Counts
==============================

  2486  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:198
  1836  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:68
  737  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/workers.rb:78
  333  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/context.rb:238
  318  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:69
  214  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/tracer.rb:186
  212  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/span.rb:168
   90  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/transport/http/builder.rb:95
```

Is this normal for ddtrace to consume so much memory?

**Comment by delner** [comment]
For most processes/use cases it doesn't, however, we have seen long-running traces in worker processes like Sidekiq and Resque use more memory in some cases, typically because traces do not flush until they are completed. To address this we added in partial flushing, but it should have a larger impact than what you're seeing if this is the driver for the memory usage.

I've also seen some reports of C extensions of certain ActiveRecord database drivers causing memory leaks, that when disabled or substituted for a different driver resolved the issue. The relation between those extensions and the tracing library are unclear at this time, so I don't have a suggestion as to whether its relevant in this situation, or how it could factor in.

I'd like to understand why/how specifically your application is using this much memory. A few questions:

 - How many spans do you see per trace? Just to get a rough sense of how much data is being held in memory between flushes.
 - Despite `partial_flush: true` is partial flushing actually enabled? After configuration is complete, you'd want to check `Datadog.tracer.context_flush` to make sure its a `Partial` and not `Finished` object. There is a bug addressed in an unreleased PR where partial flushing configuration options were being ignored, so I'd make sure you're not affected by this.
 - In your output you have:
    ```
    allocated by memory (3355900) (in bytes)
    ==============================
    3147408  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/workers.rb:78
    ```
    Which points to a `Thread.new` line. Do you have details about this? And how the memory is being used?
 - What tool are you using for profiling? And what command are you using?
 - When does the memory issue occur? Immediately on startup? Gradually over time? Only under heavy load?
 - Do you have a minimal sample app we can run to replicate this kind of performance issue? Ideally a small repo with a Rails application or Gist with the code. Our tests don't replicate this kind of issue, but maybe there's something in your implementation that might reveal an edge case that needs to be addressed.

If you're able to provide us with some more info with as much detail as you can, and we're able to reproduce it on our end, then we'll be able to find and fix any memory issue we find.

**Comment by marcotc** [comment]
> ```
> allocated by memory (3355900) (in bytes)
> ==============================
> 3147408  /usr/bundle/ruby/2.7.0/gems/ddtrace-0.34.2/lib/ddtrace/workers.rb:78
> ```
> Which points to a Thread.new line. Do you have details about this? And how the memory is being used?

This seems to be the baseline overhead of a thread's stack size: https://github.com/ruby/ruby/blob/master/thread_pthread.c#L1099

On a Docker Ruby 2.5 container, we can find the configuration values used in the VM code linked above:
```
irb(main):001:0> RubyVM::DEFAULT_PARAMS
=> {:thread_vm_stack_size=>1048576, :thread_machine_stack_size=>1048576, :fiber_vm_stack_size=>131072, :fiber_machine_stack_size=>524288}
```

The `3147408` bytes reported originally are very close to `1048576 * 3` (1680 bytes off), so this leads me to believe that this is simply the baseline thread overhead. The remaining bytes likely represent other objects required internally to represent a thread that are _not_ strictly stack space.

The thread overhead should be `thread_vm_stack_size + thread_machine_stack_size`, as per VM code linked above, which would translate to `1048576 * 2`, with the provided defaults, and not `1048576 * 3`, but it seems like it is too low  of a memory footprint to represent 2 threads. I'm incline to not get too concerned with this specific line.

All remaining questions are still very much relevant.

**Comment by marcotc** [comment]
👋 @agyant, we've recently shipped memory improvements across many parts of the tracer in [0.41.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.41.0). Would you be to upgrade and let us know if you see any memory improvements?

**Comment by agyant** [comment]
Thanks marcotc we've made some changes from our side and it'll make it difficult for us to test the improvement at the moment.
I'll close it for now, I'll reopen this if we see it in other repos.
Thanks!
