### ISSUE TITLE
Using rake integration for long-running tasks

### ISSUE THREAD

**Issue by al-kudryavtsev** [DataDog/dd-trace-rb#1040]
Hello!

I noticed a problem with rake integration for long-running rake tasks (i.e. a task running between application deployments). It doesn't report any traces. I assume that's because of sampling since there is a single root trace for the whole run.
 
One workaround I found is to use MANUAL_KEEP flag on the span and to enable partial flush. However it leads to huge traces and crashing browser tabs.

Another approach that worked pretty well is disabling the rake integration completely and manually instrumenting the long-running worker. However, there are downsides: a single application may have multiple rake tasks, some of which are executed by cron (short running tasks) - those can benefit from rake integration. Basically I want to selectively disable the integration for some of the rake tasks in the same rails app. Currently we do it using the environment variables, but it has some downsides too - the env vars are configured in a separate repo so it's a bit cumbersome.

I would appreciate if you could shed some light on two things:
* Are we doing something wrong with long-running traces? Is it expected to have the issue with trace not reported in the default configuration with rake integration?
* Could there be a better way to selectively disable rake integration in the application (maybe annotate the rake task somehow?)

Thanks!

**Comment by delner** [comment]
This is a tricky situation with long-running traces; as you pointed out they can generate millions of spans and it can be difficult to get a meaningful picture from such a large trace. Rake is particularly prone to this kind of issue, because there is such great variability between rake tasks (some are simple, short migrations, others are long running jobs.)

Generally speaking I think if possible, it's best to try to break up long-running jobs into smaller trace segments, so you can get some meaningful granularity. You could relate these segments together perhaps with a common tag.

If that's not possible, then yes, pruning the trace size down or summarizing it with a single span would also be a reasonable approach. One way you could approach this is using the processing pipeline to modify the traces before they're written out. If you have well known rake tasks whose instrumentation you'd like to drop you could use the pipeline to filter those out.

In the future, I would also like to provide a means of disabling tracing within a specific context, e.g. something like:

```ruby
def foo
  Datadog.disable_tracing do
    # Your uninstrumented code here..
  end
end
```

This doesn't exist today, and I'm not sure if this would work as I hope it might, but it would be good to have this kind of feature to grant more fine-tuned control over what's instrumented. Perhaps this would be useful in your situation.

**Comment by al-kudryavtsev** [comment]
Thanks! Using a pipeline is an interesting approach, basically we can do a specialized sampling and filtering in this case.

I think we'll stick to having rake integration disabled for specific tasks & manually instrumenting them in a more granular way for now. Will look forward to any improvements in the long-running traces handling.

**Comment by delner** [comment]
Okay, thanks for bringing attention to this! Going to close this for now, but feel free to post again if you have more questions.
