### ISSUE TITLE
Internal error during HTTP transport request

### ISSUE THREAD

**Issue by mhenrixon** [DataDog/dd-trace-rb#1085]
In most of our services the following error is frequent:

```
E, [2020-06-17T09:26:41.360420 #9] ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.36.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: execution expired Location: /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
```

In one of our services, this is basically the only thing that is logged, even though when I look at the console output of the container the _request logs_ are there. We use Lograge for our logging. 

Do you have any idea what might be going wrong? First of all, why this error all the time? Is this what I get instead of the request logs? APM integration is working perfectly and there I can see the requests.

The logs are just timing out trying to send them I guess. Would really like to get to the bottom of this as I am currently in need of finding some information and no logs are present even though I know they should be.

**Comment by marcotc** [comment]
👋 @mhenrixon, when you mention "request logs", are you referring to the [log collection part of Datadog](https://docs.datadoghq.com/logs/)?
This library, `ddtrace`, is responsible for the [APM component of Datadog](https://docs.datadoghq.com/tracing/). We have a small overlap with logs (when correlating logs and APM traces), but are not actually responsible for the collection or log shipping.
I can point you in the right direction if logs are you main issue here, please let me know if so.

Regarding the error reported in you issue, it comes from `ddtrace` failing to write a trace to your Datadog Agent instance. These are not uncommon if rare, but should not be frequent. The `execution expired` you are seeing is a timeout from the Ruby side, while trying to send an HTTP request to the Datadog Agent, and normally happens when you have very large traces (normally long-running) or you agent is overloaded (too many simultaneous connections or too high of CPU usage). Do you have any of these scenarios in your environment?

**Comment by marcotc** [comment]
Hey @mhenrixon, just wanted to follow up and see if this issue persists. Given it's a holistic environment issue, I understand that the circumstances might have changed since our last exchange.

**Comment by mhenrixon** [comment]
Actually, we switched from datadog due to legal reasons (we are by law required to self-host our data in Germany). Now running a prometheus based solution. 

Since I won't be able to follow up on this I recon it is better to close the issue for now.

**Comment by akhil-naidu** [comment]
@marcotc 
I am actually facing the same issue, or might be a similar issue, which was mentioned by @mhenrixon at the start of this Issue #1805

Under his circumstances, he might be wishing to switch to different service, but I guess it is not a feasible scenario for everyone. So I would like to reiterate the same issue.

## Reported Error
`[2020-12-05T05:04:24.671482 #245]  WARN -- ddtrace: [ddtrace] DATADOG TRACER DIAGNOSTIC - Agent Error: Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Net::OpenTimeout error:execution expired`

This above mentioned is an error I was facing in Heroku.

## My procedure in Configuring Datadog
1. Install The build pack
2. Configured my API according to the documentation

By looking at this screenshot, I was able to confirm that my configuration was not flawed
![Capture](https://user-images.githubusercontent.com/11688537/101234647-2457a100-36e7-11eb-8ca8-e7bf5f1c6b98.PNG)

## How I tried to Resolve this
`### Trial 01:` After a few hours of error analysis, I came across this issue https://github.com/DataDog/dd-trace-rb/issues/1065#issuecomment-639013786 which is kind of looking promising but failed to ease the error.

`### Trial 02:` Now I started digging into the documentation and arrived at this [section](https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#configuration) which talks about the different environment variables. 

I played with almost all variables and spend around a day testing all possible variables and reinstalling the entire Heroku Dyno and many other, but all of this is of no use.

## Future Updates, From My Side
Here I am going to update some notable points which I came across to resolve this issue.

**Comment by marcotc** [comment]
👋, @akhil-naidu, could you try increasing the timeout and see if it helps. You can configure the transport with a custom timeout like so:

```ruby
Datadog.configure do |c|
  c.tracer.transport_options = proc { |t|
    t.adapter :net_http,
              Datadog::Transport::HTTP.default_hostname,
              Datadog::Transport::HTTP.default_port,
              { timeout: 30 }
  }
end
```

Feel free to add `c.tracer.transport_options = ...` to your existing `Datadog.configure` instead of creating a new one.

Our default timeout is actually 1 second, which is too optimistic. It makes sense with our flush interval (every 1 second), and when the agent runs on the same host, but Heroku might be pushing that timeout.

Let us know if this helps you!

**Comment by jshah** [comment]
> 👋, @akhil-naidu, could you try increasing the timeout and see if it helps. You can configure the transport with a custom timeout like so:
> 
> ```ruby
> Datadog.configure do |c|
>   c.tracer.transport_options = proc { |t|
>     t.adapter :net_http,
>               Datadog::Transport::HTTP.default_hostname,
>               Datadog::Transport::HTTP.default_port,
>               { timeout: 30 }
>   }
> end
> ```
> 
> Feel free to add `c.tracer.transport_options = ...` to your existing `Datadog.configure` instead of creating a new one.
> 
> Our default timeout is actually 1 second, which is too optimistic. It makes sense with our flush interval (every 1 second), and when the agent runs on the same host, but Heroku might be pushing that timeout.
> 
> Let us know if this helps you!

If you're setting the tracer hostname, make sure to set it during the adapter update as well, the `Datadog::Transport::HTTP.default_hostname` will not read the `c.tracer hostname: hostname`

```ruby
hostname = ...

Datadog.configure do |c|
  c.tracer hostname: hostname
  c.tracer.transport_options = proc { |t|
    t.adapter :net_http,
              hostname,
              Datadog::Transport::HTTP.default_port,
              { timeout: 30 }
  }
end
```

**Comment by dlinch** [comment]
FYI The syntax for the configuration of the gem has updated, if you see errors like `undefined method 'use' for <Datadog::Core::Configuration::Settings>`, change all usages of `c.tracer` to `c.tracing`.
