### ISSUE TITLE
WARN -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION

### ISSUE THREAD

**Issue by gingerlime** [DataDog/dd-trace-rb#1112]
Just curious, but why is this a warning log? shouldn't it be `info`? (also the ALL CAPS feel rather alarming)

**Comment by marcotc** [comment]
Hey @gingerlime, welcome back!
Startup logs have been introduced across all Datadog tracer libraries in an effort ease reporting of the application environment during startup: https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/?tab=ruby#startup-logs

These log lines are in all uppercase to make them more visually distinguishable in production logs.

The reason they are WARN level in `ddtrace` is because `Datadog.logger` defaults to WARN level or above. Because of our intent to have these log lines displayed by default, we could either lower the default log level or increase priority of the startup log message. Lowering the default log level, to INFO in this case, would result in a more verbose log output out of the box. Changing the log level on this new startup log line turned out to have a smaller impact, thus we chose to implement as WARN.

If you want to suppress this startup log line you can set the environment variable: `DD_TRACE_STARTUP_LOGS=false`. One recommendation we have is to not suppress it in production.

**Comment by gingerlime** [comment]
Hey @marcotc 👋 

Sorry, but semantically it just doesn't make sense to me. A warning is something that has a certain meaning. Using ALL CAPS also is associated online with shouting. You're doing both! And in most cases, there's nothing to warn about, and nothing to shout about either. It's an informational message at best (maybe even a debug one).

Having to manually silence it is nice, but still feels wrong. I would say it should be the opposite. If you want to debug/check what the tracer options are, you can use a flag to show you this info, e.g. `DD_TRACE_STARTUP_LOGS=true` (and set it to `false` by default).

Just my 2 cents / personal feeling about it. It's hard for me to say what others might think/feel about it.

**Comment by marcotc** [comment]
@gingerlime, I discussed this issue with our team and we are making changes to lower it to INFO level: #1120.

Thank you again on your feedback: hearing directly from developers like yourself gives us a very strong indication on what's working and what's not.

Sorry for the troubles that this caused, we should have these changes out on the next release.

**Comment by gingerlime** [comment]
Sorry for the delay @marcotc. No trouble at all. Really happy to know that my voice was heard, even on a fairly subjective issue like this one. I really appreciate it.
