### ISSUE TITLE
Override env in `before_flush`

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#1174]
Given a setup where we have `DD_ENV` environment vars set in our datadog agent pods, is it possible to override those on a span level?  Specifically, I'd like to be able to do something like this in `before_flush`:

```ruby
Datadog::Pipeline.before_flush(
  Datadog::Pipeline::SpanProcessor.new do |span|
    some_prop = span.get_tag('tag')
    if some_prop.present? && some_prop == some_value
      span.set_tag('env', 'non-std-env')
    end
  end
end
```

The impetus being that we would like to remove certain spans from our main production APM, but would still like to see them under a different environment.  

I tried the above, but I didn't see the new environment get created, so I'm guessing the `DD_ENV` var is overriding it.

Perhaps there's a better way to achieve this?

Thanks!

**Comment by marcotc** [comment]
Hey, @mscrivo, if you want to completely remove some spans, you could use the `Datadog::Pipeline::SpanFilter` pipeline filter, instead of `Datadog::Pipeline::SpanProcessor`:
https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#filtering

I don't think we support multiple environments under the same trace, as this would case weird reporting for that tracer later down the pipeline.

**Comment by mscrivo** [comment]
I see, thanks for the clarification!
