### ISSUE TITLE
Best practice for tracing across threads in a Ruby / sinatra app

### ISSUE THREAD

**Issue by jhtib** [DataDog/dd-trace-rb#1460]
We have a Sinatra app that uses a ThreadPool to call multiple services concurrently. I have tried to assign the context to a variable and then assign back within the thread. Such as this:

```
  class ThreadPoolWithRequestStore
    def self.run(&block)
      store_id = RequestLocals.current_store_id
      context = Datadog.tracer.provider.context
      ThreadPool.run do
        Datadog.tracer.provider.context = context
        RequestLocals.set_current_store_id(store_id)
        block.call
      end
    end
  end

```

Unfortunately our results are not ideal with this as an example. 

![Screen Shot 2021-04-12 at 3 37 14 PM](https://user-images.githubusercontent.com/61478133/114471254-27870000-9ba5-11eb-839b-47fdfef36563.png)

The basic idea is there but it is clearly not optimal. Is there a running example that shows distributed tracing working with threads? Do you think I'd need to clone / dup the context when passing it in?

**Comment by delner** [comment]
With a trace model that is bound together by "parent-child" relationships, this might be technically correct even if the flame graph is clearly not optimal (as I would agree.) To confirm this is the case, I'd want to see whether the top level blue/purple spans that are directly below the green spans have a parent ID that matches the green span's span ID.

Distributed tracing doesn't really apply here super well because distributed tracing assumes synchronous execution spanning across multiple services, whereas in your example you have one service with asynchronous execution. Yes, it may make sense to somehow relate the segments of the trace across execution contexts (main thread --> worker threads) via some mechanism similar to distributed tracing, but "parent-child" model is for synchronous behavior typically.

We're actually in the process of examining this behavior and alterations we could make to better support this kind of asynchronous behavior. Sharing this example is actually very timely in this sense, so thank you @jhtib!

I don't yet have an answer on how to "fix" this, but if you have any thoughts/suggestions about what you'd expect to see, I would like to hear those.

 - What would you expect the visualization to look like?
 - How would you expect to associate traces crossing threads? (Something other than setting `tracer.provider.context=`?)

We're going to continue to develop a solution for this on our end but we'd love to hear user ideas we can incorporate while we do just that.

**Comment by delner** [comment]
> Do you think I'd need to clone / dup the context when passing it in?

You could try this as well; that Context object is mutable, so its possible the parent ID might be changed by the other threads which might contribute to the funkiness.

**Comment by jhtib** [comment]
Within the context, is all we care about trace-id and span-id? would just assigning those make more sense? Thx for help on this. We've been working also with creating spans for each thread but with mixed success. 

I saw this issue which has some in-depth discussion:
https://github.com/DataDog/dd-trace-py/issues/1184

**Comment by ivoanjo** [comment]
I spotted this as I was going through old tickets.

We've since introduced the `#to_digest`/`continue_from` mechanism that exactly can be used to manually propagate context between threads, here's an example of how to do it: https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#between-threads .

I'm going to go ahead and close this ticket for now, please do feel free to open a new one if there's any questions we can still help out with :)
