### ISSUE TITLE
Consider moving railtie to "ddtrace/rails"

### ISSUE THREAD

**Issue by ejholmes** [DataDog/dd-trace-rb#149]
It's a bit unnerving to install the ddtrace gem and have [this Railtie](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace.rb#L29-L59) automatically loaded. In some instances, people may want to be explicit about configuring their rails app and middleware.

It would be nice if the railtie required an explicit require:

```ruby
require 'ddtrace/rails'
```

Otherwise, we have to jump through some hoops to ensure that `require 'ddtrace'` is called before rails is loaded.

**Comment by delner** [comment]
I think we could strike this line https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/rails/patcher.rb#L45 then users could add `require 'ddtrace/contrib/rails/railtie'` to their `application.rb` file. Would want to make sure that things still load properly if we try that.

@ejholmes does that sound reasonable? Or do you have any other suggestions for implementation?

**Comment by delner** [comment]
@ejholmes I know this has been a long time coming, but we do have #552 up for review that addresses this.

Also, for what it's worth, in the current code you can add `DISABLE_DATADOG_RAILS` environment variable as `true` to prevent the Railtie from loading. That has been a feature since #173 (not long after this was opened.)

**Comment by delner** [comment]
This should be solved now between the changes in #173 and #552 . Closing this issue. Please feel free to re-open if you feel like it needs further consideration!
