### ISSUE TITLE
tracer logging info level logs to STDOUT though the log level is set to ERROR

### ISSUE THREAD

**Issue by paynegreen** [DataDog/dd-trace-rb#1565]
### Datadog Configuration
`ddtrace (0.50.0)` with configuration
```rb
 Datadog.configure do |c|
    tracer_options = {
      enabled: true,
      hostname: hostname,
      port: port,
      env: Rails.env,
    }

    if Rails.env.test? || Rails.env.development?
      tracer_options[:transport_options] = proc { |t|
        # Set transport to no-op mode. Does not retain traces.
        # Alternatively, you can provide a buffer to examine trace output.
        # The buffer must respond to '<<'.
        # set to $stdout if you want to see them
        t.adapter :test
      }
    end

    c.logger = Rails.logger
    c.tracer tracer_options
    c.analytics_enabled = true

    c.use :rails, service_name: service_name
  end
```

### Logs
I only see the following **INFO** logs:
```
E, [2021-06-22T10:55:51.658326 #149] ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.50.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: undefined method `new' for BigDecimal:Class Location: /usr/local/bundle/gems/multi_json-1.15.0/lib/multi_json/adapters/oj.rb:34:in `load'
```

**Comment by marcotc** [comment]
👋 @paynegreen, thank you for reporting this issue.

The log you linked is an error level log:
```
E, [2021-06-22T10:55:51.658326 #149] ERROR -- ddtrace: ...
```

This leads me to think that `c.logger = Rails.logger` is working correctly, and respecting the Rails log level.

Regarding the error:
```
undefined method `new' for BigDecimal:Class Location: /usr/local/bundle/gems/multi_json-1.15.0/lib/multi_json/adapters/oj.rb:34:in `load'
```

This seems to be caused by the deprecation of `BigDecimal.new` since Ruby 2.7: https://github.com/ruby/bigdecimal#which-version-should-you-select
It seems like one of your gems, likely `oj` is still using the old `BigDecimal.new` syntax. If you are able to update `oj` this error might go away.
I checked `multi_json-1.15.0`, and I don't see any uses of `BigDecimal.new` there.

Please let me know if this responds to your concerns here.

**Comment by paynegreen** [comment]
👋🏾 @marcotc your suggestion on updating the `oj` gem fixed the issued. Thank you 🙇🏾‍♂️
