### ISSUE TITLE
Add Generic Rails ActiveJob integration

### ISSUE THREAD

**Issue by bensheldon** [DataDog/dd-trace-rb#1633]
I'd like to propose a tracing integration for Rails Active Job generically that is not dependent upon any particular backend (e.g. sidekiq, delayed_job, etc.). ActiveJob is instrumented with ActiveSupport Notifications and I believe that it could trace:

- enqueues (count)
- executions (count, duration)
- errors
- retries

I've read this [comment](https://github.com/DataDog/dd-trace-rb/issues/695#issuecomment-465740811) about contributing and wanted to feel out interest and advice before committing myself. I'm the author of [GoodJob](https://github.com/bensheldon/good_job), an ActiveJob backend, and imagined a generic adapter would be more broadly beneficial than one specific to GoodJob. Thank you!

**Comment by delner** [comment]
Regarding adding new integrations, we've since added [this developer guide](https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md#writing-new-integrations) and [contribution guidelines](https://github.com/DataDog/dd-trace-rb/blob/master/CONTRIBUTING.md) that have some more details about building and submitting new integrations. It may not have all the information you require, but we'd happily expand upon that documentation where there are gaps to support your contribution and other future ones from the community.

Regarding ActiveJob, I'm down with capturing more frameworks from a single integration. Is the proposed ActiveJob instrumentation a replacement for existing integrations, or supplementary? Specifically, do you expect to see a trace with `ActiveJob-->Sidekiq-->(Job operations)` or just `ActiveJob-->(Job operations)` for the same process running ActiveJob/Sidekiq?

It'd be awesome to capture all the things you listed at the ActiveJob level, if possible, but whatever is added shouldn't preclude richer instrumentation at the deeper job-framework level (e.g. some tag specific to Sidekiq.) Similarly, I wouldn't want the job framework instrumentation to be aware or dependent upon ActiveJob in case it wasn't employed by a user. Right now some of these frameworks are ActiveJob aware, but an ActiveJob integration could extract that responsibility and improve upon them in that way.

Just some thoughts. Let me know what you think!

**Comment by bensheldon** [comment]
Thanks for pointing me to those resources! 🙏 

>  Is the proposed ActiveJob instrumentation a replacement for existing integrations, or supplementary?

Separate. My interest in this is primarily to allow users of GoodJob to have tracing, and that could be accomplished by instrumenting ActiveJob directly. I do think there is an opportunity to work towards something more comprehensive in the future. I could see 2 stages:

1. Have a standalone `active_job` integration that would be used alone or in place of a specific backend integration (e.g. `sidekiq`). _⇦ the focus of this proposal_
2. Backend integrations (e.g. `sidekiq`) could be updated to remove duplicated functionality so that one might run both the `active_job` integration _and_ `sidekiq` for deeper tracing. Though this could be complicated because, as you note, one could run Sidekiq without necessarily running ActiveJob.

**Comment by bensheldon** [comment]
I have opened up a PR (#1639) with the initial instrumentation of ActiveJob's `perform`; it's passing CI 🎉    

I would like some feedback to ensure that there isn't any merge-blocking problems with it before adding additional instrumentation for enqueues, etc. Thank you!
