### ISSUE TITLE
Metrics are not sent from Resque jobs

### ISSUE THREAD

**Issue by romiras** [DataDog/dd-trace-rb#1710]
For some reason metrics are not sent from Resque jobs in Rails application.

    DATADOG_CLIENT.increment('bbb', by: 1, tags: ['step:foo'])

While `app_boot.count` is sent and shown on dashboard graph.

config/initializers/datadog.rb

```ruby
unless Rails.env.test? || ENV['DISABLE_DATADOG'].present?
  require 'datadog/statsd'

  if Rails.env.development?
    Datadog.configure do |c|
      c.use :rails, service_name: "#{`whoami`}-rails-app"
    end
  else
    Datadog.configure do |c|
      c.use :rails, service_name: "#{Rails.env}-rails-app"
      c.use :resque, { service_name: 'resque' }
    end
  end
  # Create a DogStatsD client instance.
  DATADOG_CLIENT = Datadog::Statsd.new('localhost', 8125)

  DATADOG_CLIENT.increment('app_boot.count', tags: ["env:#{Rails.env}"])

  at_exit do
    # release resources used by the client instance
    DATADOG_CLIENT.close()
  end
end
```

Gems:
ddtrace (0.49.0)
dogstatsd-ruby (5.0.1)

What I'm doing wrong?

**Comment by marcotc** [comment]
👋 @romiras, because Resque uses forking during job execution, my best guess where is that `DATADOG_CLIENT = Datadog::Statsd.new` does not handle forking transparently, thus breaks when a fork happens. This was actually fixed just today in the statsd gem: https://github.com/DataDog/dogstatsd-ruby/releases/tag/v5.3.0.
If this is indeed the issue, I recommend upgrading your `dogstatsd-ruby` to 5.3.0.

If that doesn't work, you can also take a look at [Resque's hooks](https://github.com/resque/resque/blob/master/docs/HOOKS.md#worker-hooks), specifically the `Resque.after_fork` hook. Re-initializing the statsd object there will likely also fix the issue.

Let us know if these suggestion work for you.

**Comment by romiras** [comment]
@marcotc I've created a sample test application to test it. Looks good!
https://tinyurl.com/3tw6d4u7
