### ISSUE TITLE
DD_SERVICE env var or Datadog.config.service get ignored

### ISSUE THREAD

**Issue by pcriv** [DataDog/dd-trace-rb#1716]
I'm trying to integrate dd with one of our ruby services (non rails)
Using the auto-instrumentation approach I get a bunch of services for each integration. So I have rack, mysql2, net/http... etc.
When I would expect to have all this traces grouped under the name of our service set with the `DD_SERVICE` env var or the ` Datadog.config.service` property.

Any idea if this is a bug or miss-configuration?

**Comment by marcotc** [comment]
👋 this is the current intended behaviour when setting `DD_SERVICE`: it currently only affects custom instrumentation calls (e.g. `Datadog.tracer.trace('my.operation') { ... }`).

This limitation there to maintain backwards compatibility, given `DD_SERVICE` was introduced late in `ddtrace`. If we changed every service name to `DD_SERVICE`, it would break everyone's dashboards, monitors and metrics.

That being said, we plan on changing this behaviour so that `DD_SERVICE` does indeed change the service name for the vast majority of traces (any trace that is created by the Ruby application, and does not represent an external resource), but this change will come on a breaking change version bump.
We are currently aiming on having this change in either `ddtrace` 1.0 or 2.0, depending on how our other internal teams progress on work required to seemly support a single `DD_SERVICE` service name.
