### ISSUE TITLE
Don't disable app analytics

### ISSUE THREAD

**Issue by chucnm-1901** [DataDog/dd-trace-rb#1754]
If I have config like:
```
Datadog.configure do |c|
  c.use :elasticsearch, {analytics_enabled: false}
end
```
then analytics is not disabled on elasticsearch.
![image](https://user-images.githubusercontent.com/50346031/140023812-869c0bb5-6575-4410-bb91-1ef9865db72b.png)
Is there anything I am missing? Thanks

**Comment by marcotc** [comment]
👋, could you try running this line of Ruby code after your `Datadog.configure` block and see what you get back?

```ruby
Datadog::Contrib::Analytics.enabled?(Datadog.configuration[:elasticsearch][:analytics_enabled])
```

I'd expect it to be `false`, even without `c.use :elasticsearch, {analytics_enabled: false}`, as App Analytics is disabled by default.

**Comment by chucnm-1901** [comment]
@marcotc  Thank you for your help!
I followed your suggestion. but analytics is not disabled on elasticsearch.
I use filter analytics_enabled:true in the Retention Filters tab, the log is not showing. Indexed spans for App Analytics functionality aren't created. The analytics app isn't disabled. Spans indexed aren't created. How will the bill be calculated?
![image](https://user-images.githubusercontent.com/50346031/140890771-4ebae914-3404-4925-8c40-05140e35af74.png)

**Comment by marcotc** [comment]
@chucnm-1901 if you go to https://app.datadoghq.com/billing/usage, then click the "APM" subgroup, you'll see the amount of Indexed Spans the same say billing sees it. Keep in mind that the term [Indexed Span](https://docs.datadoghq.com/tracing/visualization/#indexed-span) also includes spans that were retrained by your other Retention Filters, not only App Analytics.

![Screen Shot 2021-11-09 at 4 20 38 PM](https://user-images.githubusercontent.com/583503/141026617-935c91b5-a9f7-4dc0-87a6-18128a39d695.png)

> analytics is not disabled on elasticsearch

Are you mentioned that it is not disabled because of the screenshot you linked above? ![Screen Shot 2021-11-09 at 4 20 38 PM](https://user-images.githubusercontent.com/50346031/140023812-869c0bb5-6575-4410-bb91-1ef9865db72b.png)

If it's only saying "App Analytics Status" Enabled, I wouldn't worry. But if the number of Retained spans is growing, then it is still enabled.

Did you get a chance to run `Datadog::Contrib::Analytics.enabled?(Datadog.configuration[:elasticsearch][:analytics_enabled])`? If so, what was the result? This flag is the only way to enabled App Analytics for ElasticSearch.

**Comment by chucnm-1901** [comment]
> @chucnm-1901 if you go to https://app.datadoghq.com/billing/usage, then click the "APM" subgroup, you'll see the amount of Indexed Spans the same say billing sees it. Keep in mind that the term [Indexed Span](https://docs.datadoghq.com/tracing/visualization/#indexed-span) also includes spans that were retrained by your other Retention Filters, not only App Analytics.
> 
> ![Screen Shot 2021-11-09 at 4 20 38 PM](https://user-images.githubusercontent.com/583503/141026617-935c91b5-a9f7-4dc0-87a6-18128a39d695.png)
> 
> > analytics is not disabled on elasticsearch
> 
> Are you mentioned that it is not disabled because of the screenshot you linked above? ![Screen Shot 2021-11-09 at 4 20 38 PM](https://user-images.githubusercontent.com/50346031/140023812-869c0bb5-6575-4410-bb91-1ef9865db72b.png)
> 
> If it's only saying "App Analytics Status" Enabled, I wouldn't worry. But if the number of Retained spans is growing, then it is still enabled.
> 
> Did you get a chance to run `Datadog::Contrib::Analytics.enabled?(Datadog.configuration[:elasticsearch][:analytics_enabled])`? If so, what was the result? This flag is the only way to enabled App Analytics for ElasticSearch.

**Comment by chucnm-1901** [comment]
I disabled App Analytic for ElasticSearch. I deleted  `analytics_enabled:true`. 
```
Datadog.configure do |c|
  c.use :elasticsearch
end
```
Thank you so much. @marcotc
