### ISSUE TITLE
Want to suppress error logs with a definite cause -> Connection refused - connect(2) for "127.0.0.1" port 8126

### ISSUE THREAD

**Issue by ts-3156** [DataDog/dd-trace-rb#1785]
Thanks for useful gem!

While monitoring my Rails application using datadog-agent, I occasionally see the following log.

```
E, [2021-11-24T01:58:23.101495 #5229] ERROR -- ddtrace: [ddtrace] ([APP ROOT]/.bundle/ruby/2.7.0/gems/ddtrace-0.54.0/lib/ddtrace/transport/http/client.rb:37:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
```

The above error seems to be printed when I call `Datadog.tracer.trace` while restarting datadog-agent. I would like to change the log level from ERROR to INFO for errors with a definite cause. Do you have any good solutions?

#### Reproducible code

```ruby
require 'datadog/statsd'
require 'ddtrace'

6000.times do
  Datadog.tracer.trace('debug.restart_datadog', service: 'debug_datadog_tracer') do |span|
    sleep 0.01
  end
end

# Run `sudo restart datadog-agent` immediately after starting this Ruby script.
```

**Comment by marcotc** [comment]
This is tricky one, @ts-3156, as the error `Connection refused - connect(2) for "127.0.0.1" port 8126` is very important to be surfaced if there is a persistent connectivity issue between `ddtrace` and the agent.
And it's a pretty critical error too, as this means that no traces will be sent out of the host application if the error persists.

It's also useful when there are network issues (e.g. congestion) that can happen infrequently: this error will let the user know that connect could be established at those specific points in time.

Despite that, main constraint that prevents this error from being suppressed during temporary failures (like the agent restart you mentioned) is that Datadog APM tracers will discard the payload at hand if they cannot be flushed. In other words, we don't retry when there are network failures.

This is in place because we want to reduce the amount of data Datadog tracers keep in memory in the host application.

If we had a retry policy, we could simply print `Connection refused - connect(2) for "127.0.0.1" port 8126` _only_ when the retry limit was exhausted, and you'd probably never see it in your scenario.

I'm not super sure of what's the best solution here: disabling the error altogether (through an option) seems too aggressive as you'd probably would like know if this error has been happening consistently for many minutes.

**Comment by ts-3156** [comment]
Thanks for the detailed explanation. This problem was resolved thanks to your support.

I provided datadog tracer with a new logger, because what I wanted to do is to remove the "ERROR" string from the application log to avoid unnecessary error reporting.

```
Datadog.configure do |c|
  c.logger = ::Logger.new('log/datadog-tracer.log')
  c.logger.level = ::Logger::INFO
end
```

**Comment by ts-3156** [comment]
I occasionally see this error log as well. Perhaps this error is also caused by restarting Rails(Puma, Sidekiq) or AWS EC2 instance. I'll post it here in case it's useful to someone else.

```
ERROR -- ddtrace: [ddtrace] ([APP ROOT]/.bundle/ruby/2.7.0/gems/ddtrace-0.54.0/lib/ddtrace/transport/http/client.rb:37:in `rescue in send_request') Internal error during HTTP transport request. Cause: end of file reached Location: /usr/local/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
```
