### ISSUE TITLE
Wrongly reported walltime in test runs

### ISSUE THREAD

**Issue by Drowze** [DataDog/dd-trace-rb#1837]
Hello Datadog crew 👋 

My team is starting to use more the test analysis provided by Datadog so we can more carefully track flaky tests and how our test suite grows overtime. This is very handy and a big win for us, so thank you for giving us such tool! That said, we unfortunately are facing an issue recently:

# The problem:
We have the Datadog Ruby tracer enabled in a few repositories and most of them seem to have reported walltime that seems to be about right, with exception of one repository. On that repository:
* The tests build on the CI (GitHub Actions) takes about ~6min20s
* If I manually sum the duration of all tests using DD graph tool, I see the tests are usually not taking more than 15 minutes
* The reported walltime for the tests on that repository is *always more than 30 minutes*

I think that walltime is very wrong. According [Datadog documentation](https://docs.datadoghq.com/continuous_integration/explore_tests/):
> Wall time is the real time elapsed while the test suite runs, which is less than the sum of all test times when tests are run **concurrently.**

# Some details:
About the repository:
* It is a GitHub repository named sts under Over-haul organization (this should help you debugging)
* It runs our tests in parallel in multiple machines at the same time using the [knapsack gem](https://docs.knapsackpro.com/ruby/knapsack) (note: we have the exact same setup on other two repositories, but they do not present the same problem)
* It is a Ruby repository running RSpec and using ddtrace 0.54.1

Screenshots:
* Last few commits on base branch with wrong _wall time_:
![image](https://user-images.githubusercontent.com/9031589/150103719-9cc23b6a-74a1-458f-87a5-7f45c84b9195.png)
* Manual sum of tests duration using DD graph tool:
![image](https://user-images.githubusercontent.com/9031589/150105412-afe392ac-d196-48d5-9333-238e183e7fae.png)
* Average duration of the test build on our CI:
![image](https://user-images.githubusercontent.com/9031589/150104244-8c997e1d-1200-46c2-84e7-228c12075c59.png)

Please let me know if you need any more details 😄

**Comment by juan-fernandez** [comment]
hi @Drowze! Thanks for the thorough explanation.

Let me explain a bit how wall time is calculated: 

We use the CI's job URL to identify tests run in a given job, and then we calculate the time difference between the start time of the first test and the end time of the last test.

To give an example, imagine that due to some job parallelism, these four jobs have the same job URL: 
```
<-------- job 1 -------->
    <--------- job 2 --------->
                         <------- job 3 ---------->
 <--- job 4 --->
<-------------------------------------------------> calculated wall time 

----------------------------------------------------------------> t
``` 

Summing durations does not necessarily result in the calculated wall time, and the durations of each of the jobs is not enough to calculate wall time either, because it depends on when each job starts and how the parallelism is configured. 
We touch on this in this section of our docs: https://docs.datadoghq.com/continuous_integration/troubleshooting/#the-tests-wall-time-is-not-what-is-expected.

This is *not* enough to explain the discrepancy you're seeing, though. What I'm seeing is that your test executions are clustered around *two* timestamps, separated by a more or less constant time, for different commits. See jump in timestamp: 
<img width="163" alt="Screenshot 2022-01-19 at 12 45 05" src="https://user-images.githubusercontent.com/22798219/150123685-2632355f-2002-4982-8c88-a2f3c9691516.png">
<img width="170" alt="Screenshot 2022-01-19 at 12 45 24" src="https://user-images.githubusercontent.com/22798219/150124486-1fd0759b-4178-4382-963f-201e8e021e19.png">



Using the previous example, this could happen with retries: 
```
<-------- job 1 -------->                     <-----job 1 retried ----->
    <--------- job 2 --------->
                         <------- job 3 ---------->
 <--- job 4 --->
<----------------------------------------------------------------------> recalculated wall time 

-----------------------------------------------------------------------------------> t
``` 

We are not detecting any retry, though, so my questions are: 
1. Is a subset of your tests run roughly 30min after the rest of your tests?
2. Are you maybe using a tool that could be modifying timestamp calculation? (if you're doing assertions on time in your tests, you might be using a mock library that could affect `ddtrace`) 
3. Are you retrying any of the jobs running tests? We might be missing them for some reason.

**Comment by Drowze** [comment]
Hey @juan-fernandez, thanks for the thorough answer! Just found the issue thanks to your questions 😄 

So, if I get it correctly, walltime should be *no longer* than the total span time for the CI pipeline (unless I retry the jobs within that pipeline).
That said I was positive the walltime was wrong and, going through your questions, I found the culprit on the second question:

> 2. Are you maybe using a tool that could be modifying timestamp calculation? (if you're doing assertions on time in your tests, you might be using a mock library that could affect ddtrace)

Yes! Going through our codebase, I identified one particular integration test that was leaking timestamp mocking, it was something like this:
```ruby
it "works"
  # do some stuff
  Timecop.travel(30.minutes.from_now)
  # do some other stuff and assert it worked
end
```
...which was leaking that time travelling to other tests, messing up Datadog data. As a solution, I changed it to:
```ruby
# note: I changed it to use ActiveSupport TimeHelpers, but using Timecop.return should have the same effect
after { travel_back }
it "works"
  # do some stuff
  travel_to 30.minutes.from_now
  # do some other stuff and assert it worked
end
```

This indeed solved our problem 😄 
I wonder if wouldn't be viable for Datadog to check if the current time is mocked using either ActiveSupport's TimeHelpers or Timecop (which I guess are the two popular solutions for this). I'd like to see a Datadog warning coming up here!

Thanks for the help debugging @juan-fernandez, I will close this issue for now as it is not a problem on DD side. Hope my experience can help the team and/or anyone having a similar issue.

**Comment by juan-fernandez** [comment]
> So, if I get it correctly, walltime should be no longer than the total span time for the CI pipeline (unless I retry the jobs within that pipeline).

that's correct! 😄 

> I wonder if wouldn't be viable for Datadog to check if the current time is mocked using either ActiveSupport's TimeHelpers or Timecop (which I guess are the two popular solutions for this). I'd like to see a Datadog warning coming up here!

Yeah we definitely should do that. We'll also add a section in our documentation for cases in which we can't automatically detect this mocking. 

Thanks for the feedback!
