### ISSUE TITLE
Refactor request: objections to moving all reads of Rails.configuration.datadog_trace to the Railtie

### ISSUE THREAD

**Issue by nerdrew** [DataDog/dd-trace-rb#188]
Sample code:

```ruby
+++ b/lib/ddtrace.rb
@@ -36,19 +36,13 @@ if defined?(Rails::VERSION)
       module Datadog
         # Railtie class initializes
         class Railtie < Rails::Railtie
           config.app_middleware.use(Datadog::Contrib::Rails::ExceptionMiddleware)

           # auto instrument Rails and third party components after
           # the framework initialization
-          options = {}
           config.after_initialize do |app|
-            Datadog::Contrib::Rails::Framework.configure(config: app.config)
-            Datadog::Contrib::Rails::Framework.auto_instrument()
-            Datadog::Contrib::Rails::Framework.auto_instrument_redis()
-            Datadog::Contrib::Rails::Framework.auto_instrument_grape()
-
-            # override Rack Middleware configurations with Rails
-            options.update(::Rails.configuration.datadog_trace)
+            Datadog::Contrib::Rails::Framework.configure(app.config.datadog_trace)
+            Datadog::Contrib::Rails::Framework.auto_instrument(app.config.datadog_trace)
+            Datadog::Contrib::Rails::Framework.auto_instrument_redis(app.config.datadog_trace)
+            Datadog::Contrib::Rails::Framework.auto_instrument_grape(app.config.datadog_trace)
           end

           # Configure datadog settings before building the middleware stack.
@@ -56,8 +50,12 @@ if defined?(Rails::VERSION)
           # the initialization and so it's too late to add our tracing
           # functionalities.
           initializer :datadog_config, before: :build_middleware_stack do |app|
             app.config.middleware.insert_before(
-              0, Datadog::Contrib::Rack::TraceMiddleware, options
+              0, Datadog::Contrib::Rack::TraceMiddleware, app.config.datadog_trace
             )
           end
```

I can submit a PR that includes this a + removing all references to `::Rails.configuration.datadog_trace`.

My motivation for this change is changes I'd like to make to redis patcher. I want to pass config to the redis patcher (`default_redis_service` and an option to include the redis hostname in the service name, see https://github.com/DataDog/dd-trace-rb/issues/135).

Thoughts?

**Comment by nerdrew** [comment]
cc @danielni

**Comment by palazzem** [comment]
@nerdrew that sounds interesting. I didn't comment your Redis PR since I think we should tackle this one first. I think that we should provide a common way to configure our integrations (with good defaults), so having a kind of `config` object may be useful. If we follow this approach, we should propagate the change in all other integrations, maybe using your Redis PR as example before doing the same for everything else.

Let me digest the implications of that, so I can reach you with a plan. Sounds good?

**Comment by nerdrew** [comment]
That makes sense. Let me know what you think.

**Comment by palazzem** [comment]
Hello @nerdrew! As I wrote in the other PR, I'm going to close this PR since the whole library has been redesigned with a new configuration system. This specific behavior has been included with the Rails refactoring available here: https://github.com/DataDog/dd-trace-rb/pull/224

Thank you very much for this PR!
(Side note: we're preparing now the 0.11.0 release with the migration guide)
