### ISSUE TITLE
Sidekiq instrumentation not complete in traces

### ISSUE THREAD

**Issue by viraptor** [DataDog/dd-trace-rb#2056]
I've got a situation in both 0.54 and 1.0 tracer where some sidekiq actions are not inside a sidekiq trace. This happens with both redis and active_record where I see for example an `active_record.instantiation` block on its own in a trace. This is on a host which only runs sidekiq and nothing else, so it's definitely coming from that service.

This is especially annoying in the redis situation where there are many spans not captured in a job, so the traces count is artificially inflated.

The service is configured with just `tracing.enabled`/`runtime_metrics.enabled` and instrumenting `active_record`, `redis`, `sidekiq` along with others.

How can solve this / how would I provide more information to debug this?

**Comment by delner** [comment]
Thanks for sharing!

`active_record.instantiation` definitely should not be in its own trace: in 1.0, it's supposed to decorate the active trace, and have a service equal to `DD_SERVICE`/`c.service` set in your configuration.

Can you clarify how Redis is involved? Is it the same where it's not being appended to the active trace?

There are multiple possibilities for this, among them 1) active trace isn't resolving, 2) process has forked/spun off a thread async. But we're going to have to dive deeper to know what it is. The best/easiest way to do this is if you're able to help me replicate the problem on my end.

Do you have any example code you can share that helps replicate the problem? Or can you share your configuration for both Datadog and Sidekiq? Goal on my end is to run the application locally, see the same behavior, so I can then debug it.

Also can you share screenshots of the trace? So I know I have the same behavior?

**Comment by viraptor** [comment]
We've got 2 services, one has the disconnected redis commands, the other AR instantiation. One is definitely not using threads (AR), the redis one does.
I'll try to capture some stack traces for "annotating redis, but `active_trace` is nil" today to maybe we can pin point this better.

**Comment by delner** [comment]
Gotcha. If `active_trace` is `nil`, and you call `Tracing.trace`, then I would expect it to begin a new trace. So the question would be "why is `active_trace = nil` at this point?"

**Comment by viraptor** [comment]
Just a note - Other things happened in the meantime, so I'll test the Redis part of the issue next week.

For the record after some cleanup I found that the only unattached AR traces came from `active_record.instantiation: Delayed::Backend::ActiveRecord::Job` itself - so querying for jobs is not traced as part of DJ. (yes, I missed those came from DJ not sidekiq) If I can't find any customisation for it on our side, I'll raise that as a separate issue for that instrumentation.

**Comment by jennchenn** [comment]
Hi @viraptor, thanks for providing the additional details! We have done some investigating, and the reason you were seeing small redis/active_record root spans is because we currently do not have instrumentation for all the internals for `sidekiq` and `delayed_job`. Since these do not get wrapped up in a nice parent span, it results in your situation where, for example, each Redis command generates its own span.

To mitigate this, we can add in some more instrumentation for these two libraries. I have here some screenshots of what the new behavior should look like once we implement this - let me know if this works for you!
### delayed_job
![image](https://user-images.githubusercontent.com/32009013/179088096-ba423b01-4338-4042-b847-f34a3f5559da.png)
`active_record.instantiation: Delayed::Backend::ActiveRecord::Job` and related database calls would get wrapped in a span like `reserve_job` ([corresponding method](https://github.com/collectiveidea/delayed_job/blob/11e0212fb112c5e11e4555ef1e24510819a66347/lib/delayed/worker.rb#L315-L325))


### sidekiq
To cleanup all/most of the redis traces you're seeing, a few new parent spans will be introduced.

#### `sidekiq.scheduled_poller_wait`
![image](https://user-images.githubusercontent.com/32009013/179090545-2c3ca4a9-e372-415d-b109-9b4098068d9f.png)
([corresponding method](https://github.com/mperham/sidekiq/blob/7f6b2efe205a44205b614487ca49c381544ecb83/lib/sidekiq/scheduled.rb#L118-L128))

#### `sidekiq.stop`
![image](https://user-images.githubusercontent.com/32009013/179090401-2baefb70-f255-478e-baf1-39884dd88155.png)
([corresponding method](https://github.com/mperham/sidekiq/blob/7f6b2efe205a44205b614487ca49c381544ecb83/lib/sidekiq/launcher.rb#L49-L64))

#### `sidekiq.redis_info`
![image](https://user-images.githubusercontent.com/32009013/179090294-41b3f147-891c-4819-950a-6ee2a81d50c6.png)
([corresponding method](https://github.com/mperham/sidekiq/blob/7f6b2efe205a44205b614487ca49c381544ecb83/lib/sidekiq.rb#L116-L130))

**Comment by jennchenn** [comment]
I just merged in #2170, which should go into our next release. I will be closing this issue for now, but let me know once you get a chance to try out the fix if the issue still exists for you!

**Comment by viraptor** [comment]
Thank you.  Hope that addresses all the remaining cases.

**Comment by jennchenn** [comment]
Hi @viraptor, the fix has been released in [1.3.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v1.3.0)! Let me know if you get a chance to try it out
