### ISSUE TITLE
HTTP request queuing duration

### ISSUE THREAD

**Issue by ib-drct-dev** [DataDog/dd-trace-rb#2064]
I want to measure how much a request waits in a queue until it is served by an app.

There is a way to generate traces that include the time spent in a queue. The instrumentation produces http_server.queue.duration metric. Which is not exactly I need and expect.

1) Is it possible to compute queue waiting time some how from the information we have? I thought about subtracting `http_server.queue.duration` from `rack.request.duration` but `http_server.queue.duration` filters out some traces so aggregated duration values could be skewed and we won't get accurate values. Maybe there are other options?
2) Maybe it's possible to add another metric which subtracts `X-Request-Start` from the time a request has arrived in an app?
3) Why the produced metric is called `http_server.queue.duration` even it does not compute queue waiting time? Wouldn't `http_server.request.duration` be more accurate name?

https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#http-request-queuing
https://github.com/DataDog/dd-trace-rb/blob/3cbcea6f1fd240de00200b7135c907f3fd194c9a/lib/datadog/tracing/contrib/rack/middlewares.rb#L116

Thanks!

**Comment by wantsui** [comment]
Regarding metrics such as `trace.http_server.queue.duration` and `trace.rack.request.duration`:

These metrics follow the pattern `trace.<SPAN_NAME>.duration`. According to our [documentation on this metric ](https://docs.datadoghq.com/tracing/metrics/metrics_namespace/#duration), this metric records the collection/sum of all spans in a period of time:

> [LEGACY] Measure the total time for a collection of spans within a time interval, including child spans seen in the collecting service.

What this means is that the values it gives back is an aggregated number which is why the numbers can be large. As a result, when you divide this by `hits`, you can get `average`, seen in the docs as well:

> When trace.<SPAN_NAME>.duration is divided by trace.<SPAN_NAME>.hits, the result can yield an average latency, but this is not the recommended approach for calculating the average latency. Instead, refer to the [Latency Distribution](https://docs.datadoghq.com/tracing/metrics/metrics_namespace/#latency-distribution) section for average latency calculations.

As a result if you tried to do a computation via `trace.http_server.queue.duration - trace.rack.request.duration`, the results wouldn't be useful or accurate for any given request since it's aggregated information. 


If you're trying to understand latency in terms such as min/max/avg, I recommend using **[DDSketch metrics](https://docs.datadoghq.com/tracing/guide/ddsketch_trace_metrics/#pagetitle)** instead. 

- Instead of `trace.http_server.queue.duration` to understand latency, use the DDSketch metric: `trace.http_server.queue`
- Instead of `trace.rack.request.duration` to understand latency, use DDSketch metric: `trace.rack.request`


Unfortunately, I can't speak to the reasoning behind the name of the span (queue vs request) and workarounds so hopefully someone else is able to chime in on that front.

**Comment by agrobbin** [comment]
@marcotc I *think* this issue can be closed now that #2591 has been merged!

**Comment by marcotc** [comment]
Thank you, @agrobbin! You are right, we'll close this issue when 1.10.0 is released.

**Comment by ib-drct-dev** [comment]
Awesome! Thank you @agrobbin  🙌
