### ISSUE TITLE
The error metrics is not shown with GraphQL::ExecutionError

### ISSUE THREAD

**Issue by shnmorimoto** [DataDog/dd-trace-rb#2245]
**Current behaviour**
When we raise `GraphQL::ExecutionError` like the below document, the error metrics (`trace.execute.graphql.errors`) is not shown in Datadog.

[Error Handling](https://graphql-ruby.org/errors/error_handling.html#add-error-handlers)

If other error (ex. StandardError) is raised instead of `GraphQL::ExecutionError` , the metrics was shown.

<img width="878" alt="スクリーンショット 2022-08-26 20 42 52" src="https://user-images.githubusercontent.com/1239431/186896101-66431b88-5cb3-45a3-9cc0-6e4fd0591625.png">

**Expected behaviour**

When we raise `GraphQL::ExecutionError` ,  the error metrics is shown in Datadog

**Steps to reproduce**

Set up the graphql tracing manually.

```
class Graph::Schema::MySchema < GraphQL::Schema
....
    use(
      GraphQL::Tracing::DataDogTracing,
      service: 'graphql'
    )
...
end
```

Raise `GraphQL::ExecutionError` in `rescure_from`

```
    rescue_from StandardError do |e|
      Rails.logger.error e.backtrace.join("\n")
      Rails.logger.error e.message
      Sentry.capture_exception e
      raise GraphQL::ExecutionError, "some message"
```

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version: 1.3.0** 
* **Configuration block (`Datadog.configure ...`):see steps to reproduce**
* **Ruby version: 3.0.4** 
* **Operating system: ruby:3.0.4-alpine on docker**
* **Relevant library versions: graphql-ruby 1.13.0**

**Comment by idanci** [comment]
`GraphQL::ExecutionError` is rescued in graphql-ruby internally and never bubble up resulting in just adding the error to `errors` key in response and resolving the field to `nil`. From server's perspective it's not even a error, because it returns status 200 and response including the error in the body.

You can either manually in your `rescue_from` block use `set_error(e)` on and actvie span, or if you want it to always be processed by [datadog error tracking](https://docs.datadoghq.com/tracing/error_tracking/#how-datadog-error-tracking-works), add it to the root service span.

**Comment by shnmorimoto** [comment]
Thanks for the information.

I tried to set `set_error`
Currently, I got the error in the trace page.

<img width="1125" alt="スクリーンショット 2022-08-27 15 59 16" src="https://user-images.githubusercontent.com/1239431/187019071-b0f0134d-d7d1-4333-907d-e9851804953e.png">

But, errors are not yet available in error tracking.

<img width="852" alt="スクリーンショット 2022-08-27 16 03 01" src="https://user-images.githubusercontent.com/1239431/187019115-ace0ae3b-8ff7-4902-b8ea-6766bb82de9f.png">

So, I would like to set `set_error` `root service span` also.

It seems already `active_root_span` was removed
https://github.com/DataDog/dd-trace-rb/blob/v1.0.0.beta1/docs/UpgradeGuide.md#breaking-changes

I guess we can trace `parent_id` of `active_span` and get `root_span`.

I saw the documentation but could not find a way to get `SpanOperation` from `span_id`.
https://www.rubydoc.info/github/DataDog/dd-trace-rb/Datadog/Tracing

How do we get `root_service_span`? And can we set `set_error` to it?

**Comment by idanci** [comment]
`Datadog::Tracing.active_trace&.active_span&.set_error` something like that.

Root span is accessible normally in [java](https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/java/#set-tags--errors-on-a-root-span-from-a-child-span). I don't know why it was removed from ruby sdk, inconvenient, but there is not much of a choice.

**Comment by shnmorimoto** [comment]
Thanks for suggestion!

I tried to set it.
It seems `Datadog::Tracing.active_trace&.active_span` return same object as `Datadog::Tracing.active_span`

```ruby
Rails.logger.info("active span id is #{Datadog::Tracing.active_span&.id}")
Rails.logger.info("root span id is #{Datadog::Tracing.active_trace&.active_span&.id}")
```

<img width="568" alt="スクリーンショット 2022-08-27 22 31 29" src="https://user-images.githubusercontent.com/1239431/187032418-d88a25cf-0d1d-429f-93ab-cfd902f540a0.png">

I thought that if `active_trace` return `Datadog::Tracing::TraceSegment`  as per the documentation, we might be able to use `spans` in `Datadog::Tracing::TraceSegment`. But `active_trace` seems to return `Datadog::Tracing::TraceOperation`.

<img width="934" alt="スクリーンショット 2022-08-27 22 39 39" src="https://user-images.githubusercontent.com/1239431/187032884-49eecd27-7d76-4dcf-ace5-dcb46058aafc.png">

https://www.rubydoc.info/github/DataDog/dd-trace-rb/Datadog/Tracing#active_trace-class_method

Therefore, there may be no way to access root_span.

**Comment by idanci** [comment]
If there are no extra `Datadog::Tracing.trace` calls within your graphql executor or no extra nested instrumentation enabled, then indeed active_span maybe be the same as active_trace.active_span, but that is not always the case.

**Comment by shnmorimoto** [comment]
I see. Thanks for the explanation.

**Comment by TonyCTHsu** [comment]
Chiming in a bit late to provide what I have before digging too deep into this.

In order to make [error tracking work](https://docs.datadoghq.com/tracing/error_tracking/#how-datadog-error-tracking-works), datadog expect the error to be tagged at the [service entry span](https://docs.datadoghq.com/tracing/glossary/#service-entry-span) (in short, the first span on flamegraph with change of colour.). According to the snapshot provided, it seems like the implementation is tagging the error on the second spans instead of the first one.
![Screenshot 2022-08-29 at 10 54 48](https://user-images.githubusercontent.com/16049123/187163966-75e835e9-f326-40cf-b502-501f8e3f5459.png)

I was also surprised that the active span in `rescue_from` block is not the service entry span, but this could vary based on different user cases.

GraphQL endpoint is advised to return 200 response with `errors` field provided. `GraphQL::ExecutionError` is a friendly object to help you accomplish that without crashing your application. Hence `GraphQL::ExecutionError` would be rescued and preventing being bubbled up. Other error, such as `StandardError`, would be bubbled up and recorded at the service entry span.

**Comment by TonyCTHsu** [comment]
👋 Hi @shnmorimoto , it looks like the issue have been clarified, do you think we could close the issue for now?

**Comment by shnmorimoto** [comment]
Yeah, we can close this ticket.
Thanks a lot @TonyCTHsu @idanci
