### ISSUE TITLE
Tracing Sinatra app should show an error in the Service APM when the app halts.

### ISSUE THREAD

**Issue by enricoribelli** [DataDog/dd-trace-rb#2254]
**Is your feature request related to a problem? Please describe.**
We are trying to setup our Sinatra based application in such a way that, when the controller answer with an`halt`, the DD Service APM reports an error under the error Dashboard of the Service.

![image](https://user-images.githubusercontent.com/9882443/188682770-bc7264a2-7fe0-4b15-a12a-f4dcef850c83.png)

**Describe alternatives you've considered**
I have tried to manually get the current active span and pass an exception to it for then: `active_span&.set_error(error)`. But I feel like this is an overkill. I don't want to create an exception every time my app `halt`s back to the caller for some reason.

**Extra**
I may have setup the App in the wrong way. Currently using `register Datadog::Tracing::Contrib::Sinatra::Tracer` which allows the DD agent to see and report:
`operations:sinatra.route`
`sinatra.request`
Also the rack instrumentation is there during DD configuration which gives us:
`operation:rack.request`

**Comment by marcotc** [comment]
👋 @enricoribelli, because `halt` can be used to [early return any HTTP response](https://github.com/sinatra/sinatra/blob/8ae87a87f38d3c7589ae0d456bc7ea598d5861c2/lib/sinatra/base.rb#L956-L957) (including OK 200 responses), we use [the default Rack server_error? logic](https://github.com/rack/rack/blob/f587034d9d2c9a8964cf6a30b32ef264b3375c6b/lib/rack/response.rb#L181), which is `status >= 500 && status < 600`. So `halt 500` will set a proper error.

It seems reasonable to me that if you are returning a non-error from `halt` (e.g. `halt 204`), I would not expect an error to be set.

I'm wondering: how are you using `halt` in your application? Could you clarify when you expect `halt` to register error and it's not?

**Comment by ivoanjo** [comment]
We haven't heard back in a long time on this ticket, so I'm going to go ahead and close it. Please do feel free to open a new one if there's anything we can help out with :)
