### ISSUE TITLE
Faraday and net/http appear as a service in the service list

### ISSUE THREAD

**Issue by davidgm0** [DataDog/dd-trace-rb#2347]
**Current behaviour**

I configured dd-trace 1.5.2 with 
```ruby
gem 'ddtrace', '~> 1.5', require: 'ddtrace/auto_instrument'

Datadog.configure do |c|
  # nothing here
end
```

My application uses faraday to call another service that is also instrumented with Datadog. When I look at a trace, I see the Faraday and the other service correctly instrumented, I see spans for the libraries and service. The component name appears also in the Faraday span. However, I also see the services `faraday` and `net/http` in the service list. `faraday` and `net/http` are not internal or external services, as I see it they are just libraries.

<img width="481" alt="trace" src="https://user-images.githubusercontent.com/82040808/199514164-0d04f561-0f63-446c-9352-74876c937e6e.png">

☝️  This looks good. The second service (last 2 spans) looks correct, and logs match as well.

**Expected behaviour**

Faraday or net/http should not appear as services in the services list. They are libraries, not other services. I have seen a number of other tickets talking about service names but I wasn't able to figure out if I this is already tracked, will be fixed, or if it's my mistake.

 If the called service would be external (not instrumented), I would still think this should not appear in the list: It is not under our control and it's not instrumented.

This shouldn't be here I think 👇 

<img width="804" alt="Screenshot 2022-11-02 at 14 23 20" src="https://user-images.githubusercontent.com/82040808/199514608-2fdb43f1-9295-44ee-94f9-4b7c3a2c9bc1.png">

I also tried using       
```ruby
  c.tracing.instrument :faraday, describes: /.*other-service-name.*/ do |faraday|
    faraday.service_name = "other_service_name"
  end
```

But I still see this service. Faraday is coloured now as part of the second service, which would make this not 100% correct (although it's me who indicated the service name)

<img width="1202" alt="second_trace" src="https://user-images.githubusercontent.com/82040808/199532999-2a8fc717-4262-4c22-892b-e6a0708af967.png">

**Environment**

* **ddtrace version: 1.5.2**
* **Configuration block (`Datadog.configure ...`):**

```
  Datadog.configure do |c|
  # nothing here 
  # DD_SERVICE set already
  end
```

* **Ruby version: 2.7.6**
* **Operating system: maOS Monterrey**
* **Relevant library versions: Faraday 1.10.2**

**Comment by TonyCTHsu** [comment]
👋 @davidgm0 , Thanks for reporting! 

Yup, you are right about this. `service` has been a historic issue that we would like to migrate away from. In the context of distributed tracing, `service` should be servers, while it has been used for categorization of components/libraries. There are plenty of work need to be done for this breaking change, including UI changes/improvements. 

To group `faraday` and `net/http` as the same service of the current application. Try if such configuration works for you 😉 
```
Datadog.configure do |c|
  c.service = 'myapp'

  c.tracing.instrument :rails
  c.tracing.instrument :faraday, service_name: 'myapp'
  c.tracing.instrument :http, service_name: 'myapp'
end
```

**Comment by Whitespace** [comment]
If you change every `service_name` to be the same, then many graphs break because all the data is in one service:

- Total Time Spent [by Downstream Service]
- % of Time Spent [by Downstream Service]
- Avg Time per Request [by Downstream Service]
- Dependency Map

Namespacing all of the auto-instrumented services works, but becomes noisy:

```ruby
Datadog.configure do |c|
  c.service = 'myapp'

  c.tracing.instrument :rails
  c.tracing.instrument :faraday, service_name: '#{c.service}-faraday"
  c.tracing.instrument :http, service_name: '#{c.service}-http"
end
```

Because Datadog recommends the auto-instrumentation, a user might miss updating this file if they change from `net/http` to `faraday`, for example.

TBH I'm extremely surprised that Datadog APM has this kind of issue out of the box when you instrument just two rails apps.  Having all the metrics for all the apps be under `postgres` or `sidekiq` is really confusing for the end user.

**Comment by davidgm0** [comment]
I mentioned in the description that I've already tried:

```
  c.tracing.instrument :faraday, describes: /.*other-service-name.*/ do |faraday|
    faraday.service_name = "other_service_name"
  end
```

And this still shows a `faraday` service in the service list, which is not correct. Right now I don't think there's a way to configure it that doesn't make `faraday` appear as a service.

**Comment by marcotc** [comment]
👋 everyone, `faraday` and `http` are have their own service names because they were set up as such many versions ago. Changing their default service name would break many dashboards and alerts: our goal is still to make such change, but in a future major version bump.

In the mean time, for any span you don't want to see as their own service, follow @TonyCTHsu's recommendation to set the service name to DD_SERVICE:
```ruby
  c.tracing.instrument :faraday, service_name: ENV['DD_SERVICE']
  c.tracing.instrument :http, service_name: ENV['DD_SERVICE']
```

@davidgm0, I see you are setting the Faraday service name to `other_service_name`: would setting it to `DD_SERVICE` instead work for your use-case? The downstream service reporting would still work correctly, as that service has its own service name.

@Whitespace, unless you care about having `active_support`, `faraday`, and `http` being measured as their own services, which I believe you mentioned you do not, I recommend setting them all to `DD_SERVICE` instead of using the suffix `"#{c.service}-..."`. This is what our Datadog demo environment does, and it looks like this:
<img width="566" alt="Screen Shot 2022-11-23 at 2 01 02 PM" src="https://user-images.githubusercontent.com/583503/203653935-57470138-b187-4bbf-a000-89b49e8406af.png">
I checked and the downstream graphs work correctly with this setup (the view from `web-store`):
<img width="626" alt="Screen Shot 2022-11-23 at 2 01 26 PM" src="https://user-images.githubusercontent.com/583503/203654193-6ce541f5-8859-4f85-a036-e6a20a64e46e.png">

**Comment by ivoanjo** [comment]
Hopefully no news is good news on this ticket, so I'm going to go ahead and close it :)

Please do open a new issue if there's anything we can help with.
