### ISSUE TITLE
pg gem tracing makes sequel configure_onto less useful

### ISSUE THREAD

**Issue by mscrivo** [DataDog/dd-trace-rb#2385]
**Is your feature request related to a problem? Please describe.**
We use sequel in our app, with a bunch of different databases and use something like: `configure_onto(DB1, service_name: 'db1')` for each DB so that we could quickly see which DB was taking the most time, or performing out of the norm in the APM "Time Spent in Downstream Service" graphs. Since upgrading to 1.x with the new pg tracing, all time spent is now showing in the `pg` service making it hard to see which DB it's actually from.

Here's a sample of how it changed post upgrade: 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/275524/202571786-3e53baff-5d82-4001-8889-072547388f8b.png">

previously the area that pg is now taking up was split between a bunch of named sequel services.

tbh I'm not sure what the right behaviour is here, perhaps there is a way to do what I want via the dashboard config? if so, please feel free to close this and redirect me to support. 

I know I can disable pg instrumentation, but the new row_count info is quite nice!  What I'm looking for essentially is to maintain the pg spans, but somehow see the total time of the sequel+pg combined spans represented by the sequel service name in the graphs if that's at all possible?

**Comment by delner** [comment]
Hey @mscrivo, thanks for the report!

I absolutely think that you should be able to configure individual databases with their own service names, as you did before: so I would like to work towards a solution there.

---

*Some quick insight into the problem domain...*

In our UX, we want to consistently assign spans to the correct `service`. That means all "Ruby work" should belong to your Ruby application (`DD_SERVICE`) and all "DB work" should belong to the DB service (`service_name: 'db1'), that way we can make these really neat, clean graphs of where time was spent.

There's a taxonomy challenge regarding spans for ORMs and DB adapters though: are they DB spans?

Historically, we said "yes, they both are", and we did this for practical reasons: mostly because we had no other way to delineate application from DB data. We would typically only see instrumentation for the ORM (most commonly `active_record`) and basically said "that's a good shorthand for DB: label it as DB service."

Now we're re-evaluating... yes they model a call to the DB, but they are created, managed by a Ruby application, and spend time measuring things done at in the Ruby code for the ORM/adapter, not the actual the DB. In that sense they are actually Ruby spans (or so I now tend to believe.)

---

*...then back to your issue.*

What's so interesting about this is that in your configuration, we now have both ORM (`sequel`) and DB driver (`pg`) spans which instrument different layers of the same thing. How should we label these spans with service names consistently?

It's my belief that:

1. `sequel` (or equivalent ORM) spans should, by default, belong to `DD_SERVICE`.
2. `pg` (or equivalent DB adapter) spans should, by default` belong to `'pg'` (or equivalent.)
3. The `sequel` (or equivalent ORM) span default service name should be reconfigurable from `DD_SERVICE` to some other value.
4. The `pg` (or equivalent DB adapter) span default service name should be reconfigurable from `pg` (or equivalent) to some other value.
5. Users should be able to configure an individual ORM client (e.g `Sequel::Database`) with its own service name.
6. Users should be able to configure an individual DB client (e.g. `PG::Connection`) with its own service name.
7. Our API should provide an easy, intuitive means of using `configure_onto` on the ORM client to configure the underlying DB client service name. (Still need to work out the feasibility of this...)

WDYT? Would behavior matching these parameters address your issue?

**Comment by mscrivo** [comment]
hey @delner, thanks for the extremely thoughtful response. I agree 100% with everything you said and I think if that were implemented, it would solve our pain point quite nicely.
