### ISSUE TITLE
Question/Documentation Request: Clarify service name behavior between 0.x and 1.x

### ISSUE THREAD

**Issue by tony-pizza** [DataDog/dd-trace-rb#2503]
I'm upgrading from 0.x to 1.x in a Rails app and following the [upgrade guide](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md). The upgrade guide [recommends setting the service name](https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#1.0-instrumentation-service-naming) for your application via `c.service=` but doesn't say why this is recommended or what exactly changed from 0.x to 1.x. I want to keep configuration and reporting as consistent as possible between versions. If I didn't set this explicitly in 0.x (or if I set it via the `DD_SERVICE` env var) can I expect the value to remain as-is after upgrading to 1.x? Or did the default behavior change? If it did change, what was the default behavior before?

Thank you!

**Comment by marcotc** [comment]
Hi @tony-pizza,. `c.service=` and `DD_SERVICE` effectively configure the same value in `ddtrace` (the value returned by `Datadog.configuration.service`).

How are you configuring the global service name before the upgrade to 1.x?

**Comment by tony-pizza** [comment]
Thanks @marcotc.

This is what things look like currently (before upgrading to 1.x):
- We do *not* set `c.service=` in our `Datadog.configure` block
- We *do* set `service_name:` option in `c.use :rails` to e.g. `production-rails-app`
- We set a `DD_SERVICE` environment variable to the name of the instance type e.g. `web`
- Calling `Datadog.configuration.service` from a production console returns `web` (the `DD_SERVICE` value)

This suggests to me that setting `c.service = ENV['DD_SERVICE']` would keep things consistent after the upgrade. *However!* I don't see `web` in our list of Services in APM. Does that suggest it's getting overridden? Or is the global service name just not used for some reason?

**Comment by marcotc** [comment]
>* We _do_ set `service_name:` option in `c.use :rails` to e.g. `production-rails-app` 
>* We set a `DD_SERVICE` environment variable to the name of the instance type e.g. `web`

Hey @tony-pizza, please correct me if I'm wrong, but I believe your configuration for `DD_SERVICE` is incorrect here: `DD_SERVICE` represents the application name, for example `billing-production-app` or `prod-backend`. Because Rails can have instances that are not strictly running web requests, it also makes sense to set `DD_SERVICE` to, for example, `prod-backend-activejob` for a background job runner, or `prod-backend-rake` for one-off or scheduled Rake tasks in production.

In your case, without knowing much about your infrastructure, it seems to me that `DD_SERVICE=production-rails-app` would represent your Rails production application correctly in the Datadog UI. If you have non-web environments for this same Rails app, you'd change the `DD_SERVICE` environment variable accordingly, if you'd like.

Let me know if this makes sense to you.
If you'd like us to support your with concrete details of your internal infrastructure (e.g. using your production configuration, with real service names, and pairing with you directly in your Service Page) we can move this conversation to a support request, as to keep such information private.

**Comment by ivoanjo** [comment]
I'm going to assume no news is good news on this one! Please do open a new issue if there's anything we can help with :)
