### ISSUE TITLE
Version conflict with debase-ruby_core_source

### ISSUE THREAD

**Issue by prateek-ap** [DataDog/dd-trace-rb#2544]
**Current behaviour**
I was just trying to play around with ddtrace and got following error while doing bundle install in my rails application

Any resolution for this?

```
psen@X1F37C2FY6 rails-vulnerability-app % bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "debase-ruby_core_source":
  In snapshot (Gemfile.lock):
    debase-ruby_core_source (= 0.10.15)

  In Gemfile:
    debase-ruby_core_source (<= 0.10.15)

    ddtrace (= 1.8.0) was resolved to 1.8.0, which depends on
      debase-ruby_core_source (<= 0.10.18, >= 0.10.16)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by ivoanjo** [comment]
Hello @prateek-ap, thanks for reporting this!

As for 1.8.0 ddtrace requires at least version 0.10.16 of `debase-ruby_core_source`, and this seems to be clashing with something else on your `Gemfile`/`Gemfile.lock`.

:a: Can you try running:

```
bundle update debase-ruby_core_source
```

and then share its output? (And if it solved the issue)

:b: Furthermore, can you could share your `Gemfile` and `Gemfile.lock`, or at least the parts that mention `debase-ruby_core_source`? It would really help in debugging this issue

**Comment by ivoanjo** [comment]
Thanks for the extra info.

The manual restriction added on the `Gemfile` is the one causing `bundler` to complain: it's being asked to figure out how to both include `'debase-ruby_core_source', '<= 0.10.15'` as well as `ddtrace` which can't currently work with that version.

If there's no specific reason for the extra restriction in the `Gemfile`, removing the `'<= 0.10.15'` from your `Gemfile` should clear the issue:

```ruby
gem 'debase-ruby_core_source'
gem 'ddtrace', '1.8.0'
```

If you needed to add `'debase-ruby_core_source', '<= 0.10.15'` because of another gem, can you share some of the details? I can reach out to the other gem's authors and work to get a fix to avoid any incompatibilities between both.

**Comment by ivoanjo** [comment]
I'm glad it's fixed! Feel free to reach out if there's anything else we can help with! :smile:
