### ISSUE TITLE
All "unrescued" exceptions show up with the resource set to our errors_controller (rails)

### ISSUE THREAD

**Issue by danielmklein** [DataDog/dd-trace-rb#2567]
**Current behaviour**
When a controller action trace from an uncaught error hits Datadog, its resource will be `ErrorsController#internal_server_error`, _not_ the controller action in which it actually occurred.

**Expected behaviour**
I expect the resource in Datadog to be the _original_ controller action, _not_ the ErrorsController action -- this makes it impossible to determine where errors originally came from.

In full transparency, I'm not super confident this is a _bug_ but maybe a misconfiguration on our part or a weird interaction with some other gem or middleware.

**Steps to reproduce**
Suppose we have the following simplistic example:
```ruby
# in a controller:
def my_controller_action
  raise StandardError("I've raised an error that won't be rescued by anything")
end
```

Furthermore, we have `ErrorsController` defined to handle `:internal_server_error` via `config.exceptions_app = routes` in `application.rb` and `match "/500", to: "errors#internal_server_error", via: :all` in our routes file.

**How does `ddtrace` help you?**
We use `ddtrace` in all of our Rails apps, and it's generally pretty great!

**Environment**

* **ddtrace version:** 1.8
* **Configuration block (`Datadog.configure ...`):**
```ruby
Datadog.configure do |c|
  c.tracing.enabled &= Rails.env.in? %w[production staging]

  # log injection is true by default as of ddtrace v1.0.0
  c.tracing.instrument :rails
  c.tracing.instrument :active_record, service_name: "core-postgres"

  # ... snip unrelated stuff
end
```
* **Ruby version:** 3.1.3
* **Operating system:** Alpine linux 3.16
* **Relevant library versions:** we also have version 3.4.0 of the `rollbar` gem installed, which adds its own error reporting middleware. This _could_ be interacting with ddtrace somehow, but I'm not sure.

**Comment by TonyCTHsu** [comment]
👋 @danielmklein , Thanks for reporting. Could you provide your version for Rails and Rack? I would also be interested with your middleware stack looks like.

**Comment by danielmklein** [comment]
@TonyCTHsu thanks for the quick response!

We are on rails 6.1.7.1 and rack 2.2.6.2.

Here's our middleware stack from `rails middleware`:
```
use Rack::Cors
use Datadog::Tracing::Contrib::Rack::TraceMiddleware
use Rack::MiniProfiler
use ActionDispatch::HostAuthorization
use ActionDispatch::SSL
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Deflater
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Datadog::Tracing::Contrib::Rails::ExceptionMiddleware
use Rollbar::Middleware::Rails::RollbarMiddleware
use ActionDispatch::ActionableExceptions
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use ActionDispatch::PermissionsPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use MyApp::ErrorMiddleware # This custom middleware rescues and logs a handful of specific (noisy) exception types
use Rack::Attack
use Rack::Maintenance
use Rack::Attack
use OmniAuth::Strategies::Facebook
use OmniAuth::Strategies::GoogleOauth2
run MyApp::Application.routes
```

**Comment by TonyCTHsu** [comment]
👋 @danielmklein , Thanks for the debugging info. It is reproducible. 

![Screenshot 2023-01-20 at 12 33 48](https://user-images.githubusercontent.com/16049123/213685970-5c9d60aa-94be-4c75-8628-dff3c36c907e.png)

There is nothing wrong with your configuration or setup, however, the suggested changed would be difficult due to some limitations. I can get back to you when I have more concrete thoughts about this.

**Comment by danielmklein** [comment]
@TonyCTHsu thanks for diving in. In the meantime, is there anything we could change in our setup/config to make this work the way I'd expect?

**Comment by TonyCTHsu** [comment]
👋 @danielmklein , before providing a patch for this, I would like to share a bit context about this issue. 

Our tracer would generate rack span from `Datadog::Tracing::Contrib::Rack::TraceMiddleware`, while `ActionDispatch::ShowExceptions` would catch the exception raised from your controller and render with another controller. That is the reason why there are one rack span and two controller spans. 

Since rack is a low level instrumentation, it would not understand which controller for a request. The reason you find `Controller#action` as  resource for a rack span is because we overwrite the trace resource from controller. Typically, this works fine with most cases, however, when `ActionDispatch::ShowExceptions` redirect to another controller, the second controller span would overwrite what was overwritten from the first controller span. 

In order to address this, my initial thought would be adding a conditional for trace resource overwrite in controller instrumentation, but I have not figured out what could be the side-effects on this change. 

You could try monkey patch this [`Datadog::Tracing::Contrib::ActionPack::ActionController::Instrumentation`](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb
). 

Change 2 occurrences ([here](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb#L40) and [here](https://github.com/DataDog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb#L59)) of
```
trace.resource = span.resource
```
to
```
trace.resource = span.resource unless trace.resource_override?
```

Let me know if it helps 😄

**Comment by danielmklein** [comment]
@TonyCTHsu so far this monkey patch has worked in my local testing. I'm going to ship it to our staging environment and will follow up once it's out there.

**Comment by danielmklein** [comment]
@TonyCTHsu this monkey patch is working great in our staging environment so far!

**Comment by danielmklein** [comment]
@TonyCTHsu (sorry for spamming you) This has now hit our production environment and it's a huge improvement. One thing I've noticed is that with this monkeypatch, if an error occurs in a `before_action`, it reports the error controller action as the resource, not the "actual" controller. Otherwise, however, this appears to be working well. Thanks for the patch!

**Comment by TonyCTHsu** [comment]
👋 @danielmklein , thanks for giving it a try.

> if an error occurs in a before_action, it reports the error controller action as the resource, not the "actual" controller. 

The current controller instrumentation measures the action method itself, which does not include `before_action`. My guess was that the code never reaches the first controller action and got invoked with the error controller. This could be the explanation of what you observed.

`before_action` instrumentation is a [feature request](https://github.com/DataDog/dd-trace-rb/issues/2100) from the community which we are looking for the improvement in the future. I will combine the need for errors controller improvement in our planning alongside with the `before_action` improvement.
