### ISSUE TITLE
Remove sorbet

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dd-trace-rb#2641]
When we added Sorbet in #1607, I documented a number of limitations that we had with its integration (see PR).

That PR also ends with

> Because our usage of Sorbet is rather simple, we can at any point switch to Steep, or any other tool, or just disable it, if it's not providing value. So we are not locked at all into its usage.

Recently the team met and decided that indeed Sorbet, with the limitations we face on our codebase (cannot include type annotations, not built for libraries, hard to run on arm64), was causing more trouble than the value we were getting from it. Furthermore, in #2449 we've added Steep and that approach seems to be working well for the modules we're using it with.

So the outcome of our decision was to remove sorbet. I'll be opening a few PRs to remove all traces of it from our repository for now.

We can always go back in the future by referencing PRs that will be linked to this issue and restoring the changes.

**Comment by GustavoCaso** [comment]
The issue we had within appsec for Sorbet in https://github.com/DataDog/dd-trace-rb/pull/2617 was referencing to `AppSec` within core, which caused us not to ignore the appsec folder anymore [here](https://github.com/DataDog/dd-trace-rb/pull/2632/files#diff-b6efeaf7c856fb7aaf37167b260c87ab44d81079038f785fdac34fbf901da5f5L7).

That also required us to change some `typed: ignore` to `typed: false` to pass CI. 

The ultimate problem was that since we are not ignoring `appsec` in the [PR](https://github.com/DataDog/dd-trace-rb/pull/261) from above, we encounter issues in which sorbet wasn't able to resolve some constants from gems, such as `rack`

AppSec, before invoking Rack specific class, make sure they are loaded, but sorbet does not know that and since the rack gem is not part of our Gemfile, calling `srb rbi gems`. We tried to include those definitions manually, but that is error-prone and tedious
