### ISSUE TITLE
Make Datadog::Tracing::Span#service_entry? public

### ISSUE THREAD

**Issue by oskarpearson** [DataDog/dd-trace-rb#2660]
**Current behaviour**

Attempts to call `span.service_entry?` when post-processing traces with `Datadog::Tracing.before_flush`. This is because `service_entry?` is a private method

**Expected behaviour**

`service_entry?` should return true or false based on the span information.

**Steps to reproduce**

Add a `Datadog::Tracing.before_flush` processor that works on a _trace_ level as follows:

```
class DatadogTraceAutoTagPropogationProcessor
  def call(trace)
    trace.spans.each do |span|
      if span.service_entry?
        # Do something here
     end
    end
  end
end
```

The above will receive an error, as service_entry? is private.

**How does `ddtrace` help you?**

This is the same scenario as https://github.com/DataDog/dd-trace-rb/issues/2655 - I'd like to selectively set tags on spans where the span is for a service-entry.

**Environment**

* **ddtrace version:** 1.9.0
* **Configuration block (`Datadog.configure ...`):** N/A - described above
* **Ruby version:** 3.1.3
* **Operating system:** MacOS
* **Relevant library versions:** N/A

** Proposed Fix **

Move https://github.com/DataDog/dd-trace-rb/blob/989b27188a6113f90bf0b3bafe25ec0f4e465b79/lib/datadog/tracing/span.rb#L203-L211 above `private` in the same file

**Comment by delner** [comment]
My general inclination here is to keep this private.

This field is meant for internal use so we can make certain internal mechanisms work. If users begin to use this method to facilitate their own mechanisms, it will make it difficult for us to refactor our internal behavior, as there will be user-dependent applications. The use of "private" here is to signal "use at your own risk", and it seems appropriate.

Our policy is to, by default, privatize & disincentivize the use of functions that (1) we are uncertain will either provide value to users, or (2) we are uncertain to the longevity of its presence or behavior.

---

Going deeper on the strategic reasoning: there are a few features that are built around the "structure of a trace." Things like "root spans" and these "service entry" spans... this kind of logic based on where a span exists within a trace is undesirable. For a few reasons:

1. An application only manages one segment of a trace: it cannot reliably reason about what precedes or follows it.
    - Code written upon the assumptions about a span being a "root" or "service entry" will break when these expectations are violated. And they *will* be violated.
2. Examining the spans that surround a trace promote coupling and co-dependence in instrumentation design. (e.g. modification of a parent span, etc.)
    - This makes instrumentation brittle (when instrumentation dependency behavior changes) and unreliable (if race conditions, asynchronous execution, or other complex behavior is present).
3. Being able to view and modify other spans out of scope means we must leave the trace in memory.
    - This significantly impedes our ability to manage performance, and impedes the development of certain features (such as streaming.)

Since 1.0, we deliberately made the choice to make this kind of strategy difficult; by hiding behavior behind `private` to discourage its use, because we don't believe its the right public API, as it would harm both users and trace library development.

**Comment by finn-orsini** [comment]
@delner Thank you for the explanation above!

For DD error tracking, the [error must be set on the service entry span](https://docs.datadoghq.com/tracing/error_tracking/#use-span-tags-to-track-error-spans): 

> Error spans within a trace are processed by Error Tracking if the error is located in a service entry span (the uppermost service span). ...

In a GraphQL service, we rescue any errors thrown by the resolvers in order to always return a well formed `errors` object. Although we've handled the error, we still want to mark these traces as errors in DataDog and see them in the Error Tracking tool. 

We are able to set an error on the active span (`Datadog::Tracing.active_span&.set_error(err)`), but this is not the service entry span and thus does not appear in the Error Tracking tools.

I was hoping to use something like `service_entry?` to filter through the spans for an active trace and set the error, i.e. 

```ruby
Datadog::Tracing.active_trace.spans.each do |span|
  if span.service_entry?
    span.set_error(err)
  end
end
```

Do you have a recommendation on how to identify a service entry span to set an error without exposing this method?
