### ISSUE TITLE
Custom traces billing

### ISSUE THREAD

**Issue by aenand** [DataDog/dd-trace-rb#2812]
Hello!

I am reaching out here since my org cannot find this information elsewhere. 

I previously reached out about adding custom span tags and span traces to our Datadog APM. After some digging through the Datadog docs I'm a bit confused on the billing of it, could anyone help explain the cost of adding custom span tags and new span traces to our APM integration?

**Comment by aenand** [comment]
Previous issue was [here](https://github.com/DataDog/dd-trace-rb/issues/2799)

**Comment by marcotc** [comment]
> As of April 25, 2023

Hey @aenand, the main cost with extra tags is `Included: Span Ingestion: 150GB per APM host, averaged across all your APM hosts; then $0.10/GB`, from https://www.datadoghq.com/pricing/?product=apm--continuous-profiler#apm--continuous-profiler.

`150GB per APM host` of traffic ingested is included with your APM plan. After 150GB, the price is `$0.10/GB`. You can estimate that each tag is a string with a key and value. The actual byte size of the key+value combined * number of spans will give you a very good estimate of how much traffic will be crated from this new tag. One trick you can do is to completely remove the tag (instead of setting it to `nil` or `""`) when you don't have a value for it, to save sending the key string with an empty value.

**Comment by aenand** [comment]
Amazing thank you!
