### ISSUE TITLE
will mysql2 gem be supported by Ruby CPU Profiling 2.0 or what are easy alternatives?

### ISSUE THREAD

**Issue by dfuentes77** [DataDog/dd-trace-rb#2832]
Not a bug or feature request.  

I'm just wondering, if the `mysql2` gem can't be used with the new Ruby CPU Profiling 2.0, is there a known set gems that could easily replace `mysql2`, that would work with the new Ruby CPU Profiling 2.0?

Have you communicated the limitation to the maintainers of the `mysql2` gem?  Just curious since I figure a huge portion of the community uses the `mysql2` gem w/ Rails, so this is a big obstacle to using the new profiling.

**Comment by ivoanjo** [comment]
Hey @dfuentes77, thanks a lot for reaching out!

I realize in retrospect that we weren't completely clear on this on the release notes, but since dd-trace-rb 1.11 [the detection of incompatible versions of `mysql2` has been improved](https://github.com/DataDog/dd-trace-rb/pull/2770). We now enable CPU Profiling 2.0 if the version of the underlying `libmysqlclient` in use by the `mysql2` gem is recent enough (more specifically, version 8 and above).

Thus, as long as you're using a reasonably-modern OS image (Ubuntu 20.04+ or similar) you should be able to use the new feature, without any extra changes. In fact, we have a large customer of profiling that has been running CPU Profiling 2.0 in production for multiple months using `mysql2` without issues. (They were the original reporter of the issue with the gem.)

As an addendum, since you asked about potential replacements for `mysql2`, I've seen some buzz in the Ruby community about `trilogy` from GitHub (https://github.blog/2022-08-25-introducing-trilogy-a-new-database-adapter-for-ruby-on-rails/) but haven't tested it yet.

Let us know if you're able to use CPU Profiling 2.0, we're pretty excited with this milestone! (And feel free to share any other feedback as well!)

**Comment by dfuentes77** [comment]
Awesome!  Thank you for the answering and thank you for the clarification.  I'm glad to hear this since we are using a sufficient version of `libmysqlclient`, so we'll be trying this out soon.

**Comment by dfuentes77** [comment]
I'm know it was presented as a difficult problem to tackle, but do we know when memory profiling will be added as well?

**Comment by ivoanjo** [comment]
Hey @dfuentes77 just a quick update that `ddtrace` now includes support for allocation and heap profiling, see https://github.com/DataDog/dd-trace-rb/issues/2881#issuecomment-2017534648 for details ;)
