### ISSUE TITLE
Signal-based profiling produces 502 Bad Gateway response from Passenger 

### ISSUE THREAD

**Issue by elliterate** [DataDog/dd-trace-rb#2976]
## Current behavior

When signal-based profiling is enabled (the default), Passenger returns a 502 Bad Gateway, claiming to have received an incomplete response from the application.

Setting `DD_PROFILING_NO_SIGNALS_WORKAROUND_ENABLED=true` fixes the application.

## Expected behavior

Passenger should return the complete application response without setting `DD_PROFILING_NO_SIGNALS_WORKAROUND_ENABLED=true`.

## Steps to reproduce

1. Run a Ruby web application with Passenger.
2. Install ddtrace.
3. Enable profiling.

## Example

See: https://github.com/elliterate/ddtrace-passenger-example

### Usage

```sh
docker-compose start
curl -v http://localhost:8080
```

### Results

* Without profiling:
  * [server-before.txt](https://github.com/DataDog/dd-trace-rb/files/12074946/server-before.txt)
  *  [client-before.txt](https://github.com/DataDog/dd-trace-rb/files/12074962/client-before.txt)

* With profiling:
  * [server-after.txt](https://github.com/DataDog/dd-trace-rb/files/12074951/server-after.txt)
  *  [client-after.txt](https://github.com/DataDog/dd-trace-rb/files/12074963/client-after.txt)

**Comment by ivoanjo** [comment]
So surprisingly enough it turns out that unlike [the previously-known incompatible gems because of signals](https://docs.datadoghq.com/profiler/profiler_troubleshooting/ruby/#unexpected-failures-or-errors-from-ruby-gems-that-use-native-extensions-in-dd-trace-rb-1110), the issue with passenger is different!

I was able to pin it down to passenger resetting a bunch of signal handlers, including the one we use for profiling when it starts. Thus, the following happens:
1. Profiler starts running, installing a `SIGPROF` signal handler used for data collection.
2. Passenger resets signal handlers
3. Profiler sends a `SIGPROF` signal, causing the Ruby app to crash because it no longer has a signal handler for this signal.

I've reported my findings in https://github.com/phusion/passenger/issues/2489, hopefully we'll be able to integrate a fix in Passenger itself.

**Comment by ivoanjo** [comment]
Btw @elliterate if you happen to have an enterprise support contract with Passenger, it may be worth dropping them a note that you're interested in that ticket. Perhaps that can help speed up stuff on their side :)

**Comment by ivoanjo** [comment]
Update: I've submitted a fix to upstream passenger, and the fix has been accepted. I've opened a ticket asking them if they could release a 6.0.19 version including them ( https://github.com/phusion/passenger/issues/2500 ).

After that version is released, I'll be able to update the profiler to auto-detect fixed passenger versions, and avoid the use of the "no signals workaround" for them :tada:
