### ISSUE TITLE
Startup logs can't be disabled via code-based configuration

### ISSUE THREAD

**Issue by lucthev** [DataDog/dd-trace-rb#3084]
After upgrading from 1.13.1 to 1.14.0, startup logs are being printed despite having

```rb
config.diagnostics.startup_logs.enabled = false
```

in the app's config.

(Note that startup logs _can_ still be disabled via the `DD_TRACE_STARTUP_LOGS` env var.)

**Current behaviour**

```
$ rails r 'puts "Done"'
I, [2023-08-28T11:13:51.048300 #39716]  INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - PROFILING - {"profiling_enabled":false}
I, [2023-08-28T11:13:51.048568 #39716]  INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - CORE - {"date":"2023-08-28T11:13:51-04:00","os_name":"arm64-apple-darwin22","version":"1.14.0","lang":"ruby","lang_version":"3.2.2","env":null,"service":"rails","dd_version":null,"debug":false,"tags":null,"runtime_metrics_enabled":false,"vm":"ruby-3.2.2","health_metrics_enabled":false}
Done
```

**Expected behaviour**

No startup logs:

```
$ rails r 'puts "Done"'
Done
```

**Steps to reproduce**
I've create a [sample app](https://github.com/lucthev/ddtrace-startup-log-repro) to demonstrate the issue. The relevant bits are https://github.com/lucthev/ddtrace-startup-log-repro/commit/d2e04c994ac28e819d649ec81804fa762cccb22b.

Running any Rails command, e.g. `rails r 'puts "Done"'`, will print the logs.

**Comment by delner** [comment]
Thanks for the report! Will take a look.

**Comment by delner** [comment]
Could you print something within your configuration code block? See where it prints relative to the logging?

My guess says `Core`/`Profiling` is running before the Rails initializer file is ran and loaded, thus the environment logger uses ENV or default settings.

**Comment by lucthev** [comment]
That's exactly what's happening, yes — if I add

```diff
diff --git a/config/initializers/datadog.rb b/config/initializers/datadog.rb
index 62d30e8..768ba95 100644
--- a/config/initializers/datadog.rb
+++ b/config/initializers/datadog.rb
@@ -1,3 +1,4 @@
 Datadog.configure do |c|
+  puts "Configuring"
   c.diagnostics.startup_logs.enabled = false
 end
```

to the sample app it prints:

```
I, [2023-08-30T10:24:28.063894 #46117]  INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - PROFILING - {"profiling_enabled":false}
I, [2023-08-30T10:24:28.065033 #46117]  INFO -- ddtrace: [ddtrace] DATADOG CONFIGURATION - CORE - {"date":"2023-08-30T10:24:28-04:00","os_name":"arm64-apple-darwin22","version":"1.14.0","lang":"ruby","lang_version":"3.2.2","env":null,"service":"rails","dd_version":null,"debug":false,"tags":null,"runtime_metrics_enabled":false,"vm":"ruby-3.2.2","health_metrics_enabled":false}
Configuring
```

**Comment by delner** [comment]
Makes sense. It's tricky because there isn't really a good way to get code configuration to run earlier, and certain activities (like profiling) need to load as soon as possible.

I think the ENV var is a good work around for now. We'll have to think about a better way of handling this. Any suggestions are most welcome!

**Comment by delner** [comment]
We did some more analysis on this issue. The cause of this is very much an issue of load order.

First, it's important to know that:

1. Whenever Datadog is configured (via `Datadog.configure`) or used (e.g. logging, auto-instrument, profiling, etc), it will cause Datadog components to be initialized with current configuration settings, and instrumentation to be applied, if configured to do so.
2. Startup logging typically occurs when the Datadog components are initialized. Currently it only logs once.

Datadog code configuration (e.g. Rails initializer) is applied in a very late step in the application startup; the main reason being we can't instrument libraries if they aren't loaded yet. So if Datadog is loaded/configured prior to this point (say via auto instrument, etc), it will initialize with ENV values and defaults. The default behavior for startup logging is on, thus it prints. The code configuration setting is not respected because it hasn't been applied yet.

Ideally, we would wait to log until the application is "ready". Unfortunately, we do not have a reliable way of determining this at load time... the logging code has no way to know whether more instructions to reconfigure the application will follow.

This did not happen before because we forced all startup logging to wait until the first trace was emitted. This behavior in itself, while OK in many cases does not work if 1) tracing is not enabled or 2) reconfiguration were to occur after the first trace.

---

**Recommendations for action:**

 - **The best way to avoid this currently is to set the `DD_TRACE_STARTUP_LOGS=false` in your application's ENV.** This should guarantee that startup logging will not occur.
 - In the immediate term, we will update the logic for startup logging to print each time Datadog is reconfigured. This way, at least the startup logs that do occur are not misleading (aka stale.)
 - In the longer term, perhaps in the next major release, I think we should consider turning this feature off by default. Doing so is a breaking change, however, so we can't do that right now.

I know this may not constitute a complete resolution, but it's the best I can see right now. If you (or anyone else) have any suggestions (immediate or long term), we'll happily consider them. In the interim, I'm going to close this issue.

**Comment by actionnick** [comment]
My suggestion would be this line https://github.com/DataDog/dd-trace-rb/blob/47f12db9aa56845a761d1d023dd9aebc1b96fd85/lib/datadog/core/diagnostics/environment_logger.rb#L34 is changed to check for more "development" contexts (checking the RAILS_ENV for example).

**Comment by ivoanjo** [comment]
@actionnick yup, we're considering a change to do that, see discussion on https://github.com/DataDog/dd-trace-rb/issues/3807#issuecomment-2255532053
