### ISSUE TITLE
Sidekiq::Shutdown errors are reported but they're normal handled exceptions

### ISSUE THREAD

**Issue by Ferdy89** [DataDog/dd-trace-rb#319]
Hi! We recently realized that DataDog is reporting many errors for Sidekiq when we deploy our application. This is because the processes need to be killed, so Sidekiq sends the `Sidekiq::Shutdown` error to its workers. Sidekiq then handled the error properly because this is the normal lifecycle of the gem. However, [the DD tracer is capturing it](https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/sidekiq/tracer.rb#L29-L37) regardless and reporting it, mistakenly triggering our monitor alerts.

Looking at how other error reporting tools do this, [they hook up to Sidekiq's built-in error handling mechanism instead](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/sidekiq.rb#L82). Sidekiq doesn't report its internal errors then.

I understand this is not an obvious bug, but I think at least it might be worth to configure.

**Comment by delner** [comment]
Hey @Ferdy89, thanks for bringing this up! Sounds like a good suggestion; we'll need to reconcile with it against how our Sidekiq tracer works. I'd be happy to take a deeper look at this and get back to you.

**Comment by delner** [comment]
Took a look into reproducing this issue, and we do indeed flag Sidekiq jobs that are aborted by `Sidekiq::Shutdown` exceptions as errors.

Good news is that if you'd like these not to report as errors, you can using our "Processing Pipeline" feature, which allows you to modify or filter out spans to customize your application's needs.

Here's a snippet I whipped up that will remove the error status from Sidekiq jobs that fail via shutdown. It preserves the back traces and exception type, but the UI will render their status as "Ok" instead of "Error":

```ruby
# Unflag Sidekiq jobs that fail with Sidekiq::Shutdown errors
Datadog::Pipeline.before_flush(
  Datadog::Pipeline::SpanProcessor.new do |span|
    if span.name == 'sidekiq.job' && span.get_tag(Datadog::Ext::Errors::TYPE) == 'Sidekiq::Shutdown'
      span.status = 0
    end
  end
)
```

Wanna give this a shot and let me know if this helps?

**Comment by delner** [comment]
Closing this given the lack of activity. Please feel free to respond here if you'd like to revisit this issue.
