### ISSUE TITLE
Trace each middleware in the Rails stack

### ISSUE THREAD

**Issue by dasch** [DataDog/dd-trace-rb#368]
I need to be able to analyze my middleware stack and find bottlenecks. I've created this patch that enables per-middleware tracing:

```diff
diff --git a/config/initializers/ddtrace.rb b/config/initializers/ddtrace.rb
index 021adf29a46..ae758df2ba9 100644
--- a/config/initializers/ddtrace.rb
+++ b/config/initializers/ddtrace.rb
@@ -37,6 +37,27 @@
   Datadog.tracer.enabled = false
 end
 
+module MiddlewareTracer
+  def call(env)
+    Datadog.tracer.trace("rack.middleware") do |span|
+      span.resource = self.class.name
+      super(env)
+    end
+  end
+end
+
+# Instrument the middleware stack after initialization so that we
+# know the stack won't be changed afterwards.
+Rails.configuration.after_initialize do
+  Rails.application.middleware.each do |middleware|
+    # The actual middleware class is wrapped.
+    klass = middleware.klass
+
+    # There are a few odd middlewares that aren't classes.
+    klass.prepend(MiddlewareTracer) if klass.respond_to?(:prepend)
+  end
+end
+
```

**Comment by delner** [comment]
Awesome. I was thinking about adding a module like this before too, so this is great to see. Probably would make some sense to "first class" such a module under the Rack integration. Then it could be available for anyone to compose into their middleware, or you could patch the stack with a function like the one above.

**Comment by dasch** [comment]
Yeah, it needs first-class support. Unfortunately, the above code caused problems with the resource naming of `rack.request` spans.

**Comment by sbeckeriv** [comment]
We did something like this but using spans. Made a module and prepended middleware classes. It wrapped the call method with something like 
 
```
Datadog.tracer.trace("rack.middleware.#{self.class.name}", span_type: "middleware")
```

at the start of each call method in the module we would check the name of the current active span if it started with rack middleware we would mark it as finished. It gives a nice visual in the charts of how long each one is taking. 

We have a whitelist of middleware to skip. Also we needed to insert a final middleware that is in the whitelist so that the middleware tracer does not run the full request.

**Comment by ivoanjo** [comment]
I've been going through old tickets and spotted this one... I'd say our recommendation nowadays is to use profiling to look at this data, since it can give a lot more context for this kind of performance analysis than tracing can.

I'm going to close this ticket for now, please do feel free to open a new one if there's something we can improve/help with :)
