### ISSUE TITLE
Sidekiq with custom service_name groups traces by model name instead of job class.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [DataDog/dd-trace-rb#398]
If I configure a custom `service_name` for my sidekiq service, then when I click on the service to view a breakdown of it's activity, instead of listing traces by job class Datadog starts listing traces grouped by ActiveRecord model. To be honest, I'm not sure how or where this model data is coming from, and it definitely seems like a bug. Removing the custom `service_name` reverts back to the expected behaviour of listing jobs by their class. Clicking on one of the strange listings (by model name) shows a further breakdown with an "origin" column containing "my custom sidekiq service | job class name", and I can from here click through to a list of traces for a specific job.

If I had to guess it seems that with the customized `service_name` my sidekiq jobs are somehow getting wrapped in another trace that's grouping them up by model name, but I'm not sure how or why this is happening, and it's not desirable. Can anyone shed some light on to what's going on here?

**Comment by delner** [comment]
Can you give me more details of your setup?

 - ddtrace version
 - Ruby version
 - Sidekiq version
 - Rails version
 - Any configuration you have for ddtrace (initializers)
 - Screenshots of the behavior you think is problematic

**Comment by delner** [comment]
If you are using `0.12-dev` or any of the `0.12.0.x` betas, you might be seeing a new ActiveRecord instantiation tracing feature we added, which adds spans for the instantiation events when ActiveRecord converts database results to Ruby objects (they're given resource names that are class names of the objects instantiated, and are assigned to the parent service which they belong.)

**Comment by undergroundwebdesigns** [comment]
@delner I am using `0.12-dev`, so that likely explains it. Are these objects meant to change the behaviour of the Sidekiq service view as I described? The behaviour seems to be strangely intermittent, after further testing I'm not sure whether it has to do with setting a custom `service_name` for sidekiq or not.

I'm willing to chalk it up to using a pre-release version of the gem, mostly just providing more info for help you guys to sort it our for release at this point. You can close this if you want.

**Comment by delner** [comment]
@undergroundwebdesigns I'd like to make sure this isn't a bug since I don't expect the behavior will change when `0.12.0` is released.

In theory, instantiation spans shouldn't change what you're seeing in the service view, since they should always be children to other Sidekiq job spans, and thus never show up as a resource under the service view.

In practice, this could happen if you are running tasks/jobs/requests through instrumented code in a Rails environment that automatically loads and configures Datadog tracing. A common example of this is if you were to add a Datadog Rails initializer file that configures the tracer as Sidekiq, but then run a Rake task that loads the Rails environment (say to get models or use ActiveRecord) but doesn't provide its own appropriate top-level parent span.

The only way to know for sure would to be to examine your configuration and traces. If you could provide screenshots or configuration, that would help pin the issue down a bit. If you'd prefer not to post such things in a GitHub issue (reasonably so since the contents might be sensitive), then you could [get in touch with our support team](https://www.datadoghq.com/support/), and we could help you dive deeper into this in a more personalized way.

**Comment by delner** [comment]
Alright, is it okay if we close this for now then, @undergroundwebdesigns ?

**Comment by undergroundwebdesigns** [comment]
Yep, go ahead.

**Comment by delner** [comment]
Okay, thanks.
