### ISSUE TITLE
Name of Sinatra tracer is not configurable

### ISSUE THREAD

**Issue by jpaulgs** [DataDog/dd-trace-rb#494]
I've got a rack / sinatra application where the config.ru looks something like:

```
      use Datadog::Contrib::Rack::TraceMiddleware

      use SinatraMiddlewareApp
      use OtherSinatraMiddlewareApp
      run Application.new
```

Unfortunately this results in datadog traces that look like

![image](https://user-images.githubusercontent.com/30516993/42977846-f202e2c8-8c0c-11e8-9e29-1593eb164b7a.png)

I would really like to be able to configure the name of the sinatra tracer but that is hardcoded at `https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/sinatra/tracer_middleware.rb` 

Or am I missing something? 

I could try putting together a PR with a little direction...

**Comment by delner** [comment]
Hey @jpaulgs ! There are two kinds of names for spans there: span name and resource name.

Span names describe the general classification of what's being done in that operation, irrespective of application domain. This value is not intended to be configurable, and is the name you're seeing displayed on the flame graph.

Resource name is a user-definable domain name that describes a domain-specific type of span (e.g. `GET /home`) which is used as a key to aggregate statistics and other useful data. This value is in manual instrumentation fully configurable, but in Sinatra auto-instrumentation is auto-generated based on properties of the Sinatra request. If you click on the `sinatra.request` span in the flame graph, the resource will show on the populated detail pane. However, it does not appear as the name of the span on the graph.

We're currently experimenting with a feature that will display resource names on flame graph instead, but I don't yet have any other details about that.

**Comment by jpaulgs** [comment]
I'm not sure presenting the resource name in the span would help as in this case it would probably be the same resource for each of the rack spans and the sinatra spans.

I get that the span names were not designed to be configurable but would it be possible to display a piece of metadata associated to the span along with the name?

**Comment by delner** [comment]
I suppose that will depend more so on the feature side of Datadog, than on our integration here. I can forward this request to our team if you like; they are always looking for suggestions like this. But I don't think we'll be able to address that in this issue here.

If I forward this along, would it be okay if I closed this issue? You could also try to reach out directly via our Slack channel if you like.

**Comment by jpaulgs** [comment]
Forward it onto the feature team and close this issue once that is done.  

To be clear this is a pretty important feature for us. Is there a public repo which I can monitor?

**Comment by delner** [comment]
I don't believe that repo is open source (for our UI/backend), so it wouldn't be publicly visible. If you'd like a channel to check back on this request, the best place to do that would be through our customer support; they create and monitor tickets for feature requests often.

**Comment by delner** [comment]
Hey @jpaulgs , I think they just rolled out a new feature to the UI that shows more information on those Sinatra spans you're seeing in the UI, so that it also displays the resource. That should help make the traces a bit easier to understand at a glance.

Going to close this issue for now, but feel free to check back here if you need anymore help on the Ruby end of things.
