### ISSUE TITLE
MongoDB tracing error upon truncating for specs

### ISSUE THREAD

**Issue by Azure7111** [DataDog/dd-trace-rb#674]
I'm currently adding the datadog agent to an app which is truncating its database each time before any specs are run. Although tracing is supposed to be disabled in the test environment the gem still tries to trace the truncation. So trying to run the specs results in the following error:

```
NoMethodError: undefined method `delete' for nil:NilClass
  /home/redacted/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ddtrace-0.18.2/lib/ddtrace/contrib/mongodb/subscribers.rb:53:in `failed'
```

It turns out that this very line was changed in the most recent version (`0.18.2`), and downgrading to version `0.18.1` makes the issue go away.

**Comment by delner** [comment]
Opened up #675 that might fix this. Can you give it a try @Azure7111?

**Comment by Azure7111** [comment]
First off let me say that I'm impressed by the quick response. Thanks!

Just gave #675 a try and it works for me! Awesome! :)

Do you still need a code sample in that case?

**Comment by delner** [comment]
@Azure7111 cool, glad to hear it's working.

If you could, it would still be helpful, because I can't say I understand how it called `failed` before calling `started`; the gem source code seemed to suggest it always happens in sequence, yet it appears that's not what happened in your application. Having a little extra insight there might help reassure us that the fix is robust enough to prevent this, or that this issue isn't symptomatic of something bigger.

I'm aiming to put this out with our next bugfix release, 0.18.3, which should hopefully roll today.

**Comment by delner** [comment]
Fix is merged to `master`, closing this.
