### ISSUE TITLE
Error logs in production: dropping trace reason: foreign span in trace

### ISSUE THREAD

**Issue by senny** [DataDog/dd-trace-rb#691]
We have upgraded to the latest DataDog agent some time ago. Since this transition we now observe regular errors in our logs about traces that are being dropped. Following are some samples:

```
2019-02-08 22:56:53 ERROR (api.go:249) - dropping trace reason: foreign span in trace (Name:TraceID) postgis.query:1dc715af9fd4ccc1 != postgis.query:50fe61b6dfa7028

2019-02-08 22:43:36 ERROR (api.go:249) - dropping trace reason: foreign span in trace (Name:TraceID) postgis.query:747cac65fc77e1eb != active_record.instantiation:42e5e71162464fda

2019-02-08 22:36:54 ERROR (api.go:249) - dropping trace reason: foreign span in trace (Name:TraceID) postgis.query:4449bd7e41ef0f5b != redis.command:2570d87c15d74f9f

2019-02-19 13:48:52 ERROR (api.go:249) - dropping trace reason: foreign span in trace (Name:TraceID) sidekiq.job:1460f4466d5f5d79 != postgis.query:3a0855ea4752665a
```

We see roughly 1000 of them per day. Do you have any hints what could be causing them?

**Comment by delner** [comment]
Very curious... not sure yet. I'll get back to you on this. Thanks for the report.

**Comment by delner** [comment]
@senny Sounds like this error is produced when a trace has spans added to it that belong to a different trace. (https://github.com/DataDog/datadog-agent/blob/c9678cb233964b9f55ec6d6dfdd74b8e9c79a990/pkg/trace/api/normalizer.go#L158-L159)

I've never seen something like this happen before, but if I were to guess, it might be related to threading or use of async frameworks. In `ddtrace-rb` there's basically one trace per thread: we keep track of this by storing a `Context` object on a thread-local variable. Whenever `trace` is called, it uses the `Context` object attached to that thread, adds its spans to that `Context`, and when the trace is completed, it flushes the spans it and disposes of the context.

So the question would be "how did spans created in one thread/context get added to different thread/context?" If we can prevent that from happening, the error should go away.

Maybe this is related to some kind of async processing or other interprocess communication. We'll need to know a little more about this to figure it out though:

1. What version of ddtrace did this issue first appear?
2. What version of the agent is being used?
3. Do we see any suspicious errors in the tracer logs? (e.g. debug flag set to true)
4. Is there any use of async callbacks, frameworks, or similar in the process?
5. Does this exclusively happen with Sidekiq? Have we seen any other processes with this problem?
6. Is there any custom configuration in the application? e.g. processing pipeline?
7. Is there any custom instrumentation/tracing present?
8. Is it possible to replicate this in isolation outside your main application? Via a sample application or test? (This would be amazingly helpful if we can manage to do this.)

**Comment by senny** [comment]
We are using `0.17.1`. I can't speak for earlier versions because we have only upgraded to the latest agent recently. The agent version is `6.9.0-1_amd64`. I didn't set the tracer to debug mode yet. How much log volume increase do I need to expect when running this in production? We don't have too much room in our log volume capacity. It happens almost exclusively on our Sidekiq worker dynos. There is a handful of cases on another dyno type, which is not build on a framework that uses threads to make certain HTTP requests (it's a low number compared to the worker dyno errors). There is a processing pipeline. You can find our config [here](https://gist.github.com/senny/77ec98a15cb6d218041f3a52c61ac534). There is custom tracing present. However, none matches the span names that are output in these errors. I haven't looked into replicating this in a sample app. I don't think I can find the time to do it at this stage.

**Comment by delner** [comment]
I'd recommend upgrading to the latest 0.19.1 over 0.17.1, although I can't say it'll definitely fix this issue. Debug mode will be very verbose, so I'd recommend activating it in a failure-tolerant environment like staging, if you can replicate it there. Can you also share your Gemfile.lock? We need to know what libraries are present and how they could be impacting operation.

To figure out what's going on, we're going to have to narrow this down a bit more. I would try disabling custom instrumentation or integrations to see if the issue seems to be linked to one of those. It's possible that custom instrumentation could break this, even if those custom spans don't show up, if they somehow have/cause a conflict with the Context object. Sharing any of that custom instrumentation would also be helpful.

**Comment by senny** [comment]
The errors are still present after upgrading to `0.19.1`. Our staging system is not monitored by DataDog at the moment. I can look into enabling that but it will take some time.

> Sharing any of that custom instrumentation would also be helpful.

Instrumentation is nested into proprietary code I am not able to share.

**Comment by delner** [comment]
@senny We haven't been able to reproduce this on our end with what we have so far.

Although I can't say it's likely to help a great deal, I might recommend upgrading to the latest versions of the trace library and Datadog agent. If the issue is still present there, and there's some more diagnostics that you can share to help reproduce this, we'd be happy to re-open this and take another look at it.
