### ISSUE TITLE
Would a PR for FastJsonAPI by Netflix be accepted?

### ISSUE THREAD

**Issue by incorvia** [DataDog/dd-trace-rb#695]
It seems to already support ActiveSupport::Notifications for instrumenting, so I think it should be pretty simple to copy the active model serializer code and replicate for FastJsonAPI but just curious if it'd be accepted.

**Comment by delner** [comment]
@incorvia We're always interested it seeing new integrations for popular frameworks, and FastJsonAPI would definitely qualify. We don't yet have a contributing guide, which is something we'd really like to add soon, but I can share some general guidelines for new integrations:

 - They can either be added directly to `dd-trace-rb` or developed as it's own gem that builds upon it.
 - They should implement the configuration API to make it easy and consistent for users. (See existing integrations as examples of this.)
 - All new integrations require documentation, unit/integration tests written in RSpec, and passing CI builds.
 - It's highly encouraged to share screenshots or other demos of how the new integration looks and works.

To get started, it's perfectly fine to essentially copy and paste an existing integration as a template and rework it for the library in question. This is usually the fastest, easiest way to bootstrap a new integration and makes the time-to-first-trace often very quick, usually less than an hour if it's a simple implementation.

In your case, since you're leveraging ActiveSupport, `active_model_serializers`, `active_record`, and `racecar` are great candidates for this, and contain some out-of-the-box behavior to leverage ASN quickly and easily.

Once you have it working in your application, you can add unit tests `dd-trace-rb` and run them locally using Docker Compose before opening a pull request. The broad strokes for this involves:

1. Building the Docker image locally (Docker Compose will do this for you automatically)
2. Start a target Ruby environment e.g. `docker-compose run --rm tracer-2.3 /bin/bash`
3. Install dependencies `bundle install && appraisal install`
4. Run tests loading the appropriate gemset using appraisal, e.g. `bundle exec appraisal contrib rake spec:fast_json_api`
5. Check linter with `rake rubocop`

Then you should be ready for code review; just feel free to open a PR and tag me for feedback.

**Comment by ivoanjo** [comment]
We quite welcome community contributions, and nowadays we even have https://github.com/DataDog/dd-trace-rb/blob/master/docs/DevelopmentGuide.md#writing-new-integrations and https://github.com/DataDog/dd-trace-rb/blob/master/CONTRIBUTING.md as contribution guides.

Since this issue is quite old (and FastJsonAPI is deprecated nowadays), I'm going to close it; pleased get in touch if we can help in any way :)
