### ISSUE TITLE
Upgrading ddtrace gem caused performance issues

### ISSUE THREAD

**Issue by jbirdjavi** [DataDog/dd-trace-rb#769]
On one of our apps, we recently upgraded the ddtrace gem from 0.15.0 to 0.24.0 and performance took a significant hit, and we started seeing OOM errors on some large requests.  We successfully did the upgrade on a number of other apps, and I don't know what's different on this one that would cause the issue.

We're also seeing some logging in /var/log/messages that doesn't show up in our other apps either.  I'm attaching the output for one request below.
[stage_g360_example_message.txt](https://github.com/DataDog/dd-trace-rb/files/3322361/stage_g360_example_message.txt)

It looks like there are lots of references to RateSampler, and it even lists other apps that we have in our datadog account, but this app shouldn't have access to them.

Ruby version: 2.3.8
ddtrace:  0.24.0 (also tested with 0.19.1), works fine on 0.15.0

[Gemfile.lock.txt](https://github.com/DataDog/dd-trace-rb/files/3322374/Gemfile.lock.txt)

[datadog_trace.rb.txt](https://github.com/DataDog/dd-trace-rb/files/3322375/datadog_trace.rb.txt)

**Comment by delner** [comment]
Just from a cursory glance, it looks like that `stage_g360_example_message.txt` file is doing `to_s` on the Rack request, which happens to have a `Datadog::Span` on it, and then its fully expanding all the references in the output from there. Seems a bit excessive, although I'm not sure if that's the reason exactly for the reported performance issues.

The reason you see the other apps come back and appear here is because priority sampling is now enabled by default, and when the trace library posts traces to the agent, it receives a response with a list of service rates to update its sampling accordingly. It might be sending back a list of all services the trace agent has received, not just the ones from your application.

This might be asking a bit much, but it would be good know what versions these performance issues first started appearing in. Is there anyways to either upgrade sequentially until you hit a version that has issues? It will help us narrow the field of possibilities (which ranges close to 1.5 years of work.) Of the largest milestones, 0.19.0 activated priority sampling by default and 0.19.1 fixed a major bug affecting priority sampling (if you're using priority sampling we suggest not using any version < 0.19.1.)

Any more information you can share would be most helpful. Thanks!

**Comment by jbirdjavi** [comment]
@delner Thanks for your response.  After doing some more digging on our end, I believe the issue is actually with lograge, not ddtrace.  It just became more apparent when we upgraded ddtrace.  Sorry about that.  If I need more assistance, I'll reopen the issue.

**Comment by delner** [comment]
Okay, no problem, let me know if there's anything else we should look at on our end.
