### ISSUE TITLE
duplicate mysql2 service

### ISSUE THREAD

**Issue by fbjork** [DataDog/dd-trace-rb#799]
I see two services for `mysql2` when I would expect just one. I see `website-mysql2` and `website-mysql`, any idea what I'm doing wrong?

I have the following configuration:

```
Datadog.configure do |c|
    c.use :rails, service_name: 'website'
    c.use :active_record, orm_service_name: 'website-active-record'
    c.use :elasticsearch, service_name: 'website-elasticsearch'
    c.use :mysql2, service_name: 'website-mysql'
    c.use :resque, service_name: 'website-resque'
  end
```

I'm using version 0.26.0.

**Comment by jeremy-lq** [comment]
@fbjork Hello. Based on the code snippet above, we'll need additional information to identify the issue. Let's move to a support ticket so someone can assist and get this addressed for you. Thanks.
https://docs.datadoghq.com/help/

**Comment by delner** [comment]
@fbjork Is your Rails application configured to use your MySQL database store through ActiveRecord? I think it's possible ActiveRecord is instrumenting some spans with one name, and the `mysql2` integration is instrumenting them with another, hence you see each name.

You could probably remedy this by passing a `database_service` option to Rails there to override the default name, so that all of the MySQL names match.
