### ISSUE TITLE
affecting spec using Array class

### ISSUE THREAD

**Issue by dfuentes77** [DataDog/dd-trace-rb#852]
We're doing this in a specific spec file:
`expect_any_instance_of(Array).to receive(:shuffle!).exactly(3).times.and_call_original`

but we're finding that the ddtrace is messing with `Array` and affecting the results of the spec.

**Comment by marcotc** [comment]
Hi @dfuentes77, could you provide us the steps to reproduce?

I tried to, but couldn't with the following snippet:
```ruby
# snippet.rb
require 'rspec'
require 'ddtrace'

RSpec.describe do
  let(:array) { [] }

  it do
    expect_any_instance_of(Array).to receive(:shuffle!).exactly(3).times.and_call_original
    3.times { array.shuffle! }
  end
end

```

```sh
$ gem install ddtrace rspec
$ rspec snippet.rb
.
Finished in 0.00886 seconds (files took 0.53343 seconds to load)
1 example, 0 failures
```

**Comment by delner** [comment]
FWIW, I don't think we patch any of the core Ruby classes/types. Is the Array in question just an `Array` or is it a subclass of `Array`?

Also you might want to consider that `expect_any_instance_of(Array)` is a very broad mock that will be affected by any gem/library that uses `Array` which is likely many of them. I'm not sure how your test is setup, but you probably want to refine your mock to constrain to just the instance of Array in question e.g. `expect(my_array)` instead of `expect_any_instance_of(Array)`.

**Comment by dfuentes77** [comment]
Thanks for the responses.  We ended up pulling that line since it wasn't required.
