### ISSUE TITLE
Are Rails 6 style replica configurations supported?

### ISSUE THREAD

**Issue by senny** [DataDog/dd-trace-rb#962]
We are switching our app to use the new Rails 6 database role configurations to configure followers:

```
development:
  ...

test:
  ...

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  follower:
    <<: *default
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>
    replica: true

  archive:
    <<: *default
    url: <%= ENV['ARCHIVE_DATABASE_URL'] %>
    migrations_paths: db/archive_migrate
```

I have configured the databases like so:

```ruby
c.use :active_record, describes: :primary, service_name: 'pg-primary'
c.use :active_record, describes: :follower, service_name: 'pg-follower'
c.use :active_record, describes: :archive, service_name: 'pg-archive'
```

In DataDog APM I now see everything under `pg-follower`. Also the queries that are executed on `pg-primary`. Anything that I am missing here?

**Comment by delner** [comment]
The ActiveRecord instrumentation ["resolves" connections](https://github.com/DataDog/dd-trace-rb/blob/4eb3ec8c6f7559dc429aadb4cfe7a2a61ccdb440/lib/ddtrace/contrib/active_record/configuration/resolver.rb) into `Hash` key equivalents.

e.g. `production` becomes:

```ruby
{
  adapter:  'postgres',
  host:     'localhost',
  port:     5432,
  database: 'my-app',
  username: 'my-app'
}
```

When you use `describes: :primary`, it uses `ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver` to resolve that symbol into this `Hash`, then normalizes it (strips out unnecessary/unwanted fields like "password", etc), finally resulting in a `Hash` of the format above.

When a connection is used during a query, it will perform this same "resolution" for the connection to produce another `Hash` of the same form. If that resulting `Hash` is identical to the "described" connection (e.g. `production`) it will tag that span with that service name, otherwise it will use default settings.

When this was built prior to Rails 6, I don't think "role" was a consideration. It's entirely possible that the resolution is not behaving as intended, or it might be normalizing away a distinctive key that the ActiveRecord connection resolver produces that distinguishes one role from the other. If the database URLs are the same except for this role, then it might explain this behavior.

It's something we should probably investigate further and issue as a bug fix if it's not working as intended. Thanks for the report @senny !

**Comment by delner** [comment]
Okay, I just happened to be browsing through the Rails repo looking at something else, and discovered [this commit](https://github.com/rails/rails/commit/d140ab073f296a2a689a4dbd58cf9434c6b2a484#diff-c226a4680f86689c3c170d4bc5911e96) which removes `connection_id` from the `sql.active_record` notification payload that we use to resolve the connection.

If it can't resolve the connection because this field is missing, this may explain why this isn't working properly. If you're not using the version of Rails with this commit, then it's likely unrelated, but something we'll have to fix when it is released.

**Comment by senny** [comment]
@delner looks like this is only in `master` yet. We are running `6.0.2.1`.

**Comment by delner** [comment]
@senny Okay good to know.

Do you have any other configuration or setup I can use to reproduce the problem? `Gemfile.lock`, dd-trace-rb version, sample connection strings (your database URLs), any other relevant ActiveRecord configuration?

I'm going to try to replicate this and take a deeper look.

**Comment by senny** [comment]
I was using `ddtrace` version `0.32.0`. Gemfile is huge but nothing should influence that part except Rails and Active Record. We are using the PostGIS adapter version `6.0.0`. That's about it in terms of AR extensions. I am observing this on a staging system, so feel free to let me know if I can log / instrument something to provide some more insights.

**Comment by delner** [comment]
Okay, so after setting up Rails 6 with replica configuration, it looks like when you drive it with the following it does produce different hash keys:

```
resolver = ::ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver.new(::ActiveRecord::Base.configurations)

(byebug) resolver.resolve(:primary_replica)
{"replica"=>true, "adapter"=>"mysql2", "username"=>"rails_readonly", "password"=>"rails", "port"=>3306, "database"=>"rails_dev", "host"=>"mysql-replica", "name"=>""}
(byebug) resolver.resolve(:primary)
{"adapter"=>"mysql2", "username"=>"rails", "password"=>"rails", "port"=>3306, "database"=>"rails_dev", "host"=>"mysql", "name"=>""}
```

The difference being that the replica has `replica: true` and the primary does not. This property is omitted from the hash key. This likely means that if you point at the same URL for both primary and replica, there will be a conflict when resolving which connection settings to use. I would expect it will take the settings for the last DB configured with `describes` in the set of conflicting keys.

However, I will point out this is a bit puzzling why this would ever be the case: in what situation would your username & host be the same, but these be actually different databases? They should never overlap. Our resolver produces this when configured with multiple roles as an example:

```
# Environment
DATABASE_URL=mysql2://rails:rails@mysql:3306/rails_dev
DATABASE_REPLICA_URL=mysql2://rails_readonly:rails@mysql-replica:3306/rails_dev

# database.yml
development:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    replica: true

# Output
resolver = Datadog::Contrib::ActiveRecord::Configuration::Resolver.new

(byebug) resolver.resolve(:primary)
{:adapter=>"mysql2", :host=>"mysql", :port=>3306, :database=>"rails_dev", :username=>"rails"}
(byebug) resolver.resolve(:primary_replica)
{:adapter=>"mysql2", :host=>"mysql-replica", :port=>3306, :database=>"rails_dev", :username=>"rails_readonly"}
```

@senny Can you provide me your connection strings? I suspect I'm not replicating your issue.

**Comment by senny** [comment]
Hi @delner 

Reading your reply finally makes me realize that our staging system aliases the primary db as `FOLLOWER_DATABASE_URL` 🤦‍♂ (there's only one database). We don't usually enable DataDog on staging so it might have been possible that it was like this for a while and no-one has noticed.

I will assume that this will not be an issue in production as `host` will certainly be different on the follower and the primary.

Thanks for helping me realize that this is not an issue and sorry for the false alarm.

**Comment by senny** [comment]
Quick update, I have added a real follower to our staging environment and instrumentation works as expected. Thanks for helping me through it and sorry again for not thinking about this earlier.

**Comment by delner** [comment]
Ahhh okay, well that makes sense then. Glad it's resolved; gave me a chance to learn a bit about how Rails does DB roles too :smile:
