### ISSUE TITLE
performance regression upgrading from 0.33.1 to 0.34.0 (rails)

### ISSUE THREAD

**Issue by gingerlime** [DataDog/dd-trace-rb#994]
I'm still investigating this, but got some early results so wanted to post something already.

After upgrading ddtrace from 0.33.1 to 0.34.0 we noticed a pretty steep performance regression with our rails app (TTFB increased by 58% from 0.45s to 1.03s).

I'm now testing it on our staging environment, and seems like rolling back to 0.33.1 improves performance again.

ddtrace 0.33.1
![Screenshot 2020-04-06 at 13 33 05](https://user-images.githubusercontent.com/524274/78554307-36590b00-780b-11ea-95fd-18e5c3bbb851.png)

ddtrace 0.34.0
![Screenshot 2020-04-06 at 13 33 14](https://user-images.githubusercontent.com/524274/78554311-378a3800-780b-11ea-8574-2947bbb286e1.png)

Wonder if anyone bumped into the same issue?

**Comment by delner** [comment]
@gingerlime Thanks for the report. Can you give us more details about how the environment is setup?

 - Ruby version
 - Rails version
 - Gemfile.lock
 - `dd-trace-rb` configuration file with `Datadog.configure`
 - Description/code sample of test case being used to measure these numbers

Goal here is to reproduce these results on our end, otherwise it will be very difficult find and address the underlying causes.

If you look at the [changelog](https://github.com/DataDog/dd-trace-rb/releases/tag/v0.34.0) this is what changed between 0.33.1 and 0.34.0:

```
### Added

- `Datadog::Event` for simple pub-sub messaging (#972)
- `Datadog::Workers` for trace writing (#969, #973)
- `_dd.measured` tag to some integrations for more statistics (#974)
- `env`, `service`, `version`, `tags` configuration for auto-tagging (#977, #980, #982, #983, #985)
- Multiplexed configuration for Ethon, Excon, Faraday, HTTP inetgrations (#882, #953)

### Fixed

- Runtime metrics configuration dropping with new writer (#967, #968)
- Faraday "unexpected middleware" warnings on v0.x (#965, #971)
- Presto configuration (#975)
- Test suite issues (#981)
```

`Event`, `Workers` and `auto-tagging` are all opt-in, test suite doesn't apply, and runtime metrics only applies under a specific edge case if you're using runtime metrics. To me, that leaves `_dd.measured`, `Multiplexed`, or maybe something related to Presto, Faraday, or the other HTTP integrations if you use them.

I'd like to see if your environment intersects with these changes.

**Comment by gingerlime** [comment]
Thanks @delner. Really sorry, but it might be a false alarm (or difficulty measuring) ... I'm still running more tests. Sorry I didn't get a chance to update this. I think we can close this. If I spot something more concrete, I'll keep you guys posted.

**Comment by delner** [comment]
No problem @gingerlime, please do share if you find anything specific about `dd-trace-rb` that hurts your application performance, as we'd very much like to address that.
